// S6 consumer cutover (decision s6-consumer-cutover-init-on-installed-copy-fixes-launchers):
// /sterling:init run from an INSTALLED plugin copy moves a consumer project off its old
// clone. (1) a sterling-launch.sh that starts claude with --plugin-dir is replaced with
// the installed shape; (2) a sterling-update.bat in the generated clone-updater shape is
// deleted, anything else is left with a notice; (3) a warning with the exact settings
// JSON when the sterling marketplace has no "autoUpdate": true; (4) the old clone is
// named for the user to delete by hand, never deleted. On an authoring clone nothing of
// this runs.
import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, copyFileSync, symlinkSync, realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderTmuxLauncher } from '../lib/launcher-tmux.mjs';
import { ensureUpdateLauncher, renderUpdateLauncher, cloneUpdateLauncherTarget, UPDATE_LAUNCHER_NAME } from '../lib/update-launcher.mjs';
import { cloneLauncherTarget, marketplaceAutoUpdate, autoUpdateWarning, cloneCleanupLines } from '../lib/consumer-cutover.mjs';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const made = new Set();
const tmp = (p) => { const d = mkdtempSync(join(tmpdir(), p)); made.add(d); return d; };
after(() => { for (const d of made) rmSync(d, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 }); });
const crlf = (s) => s.replace(/\r?\n/g, '\r\n');

/** A plugin root carrying the real templates; `git` decides authoring vs installed. */
function pluginRoot({ git }) {
  const root = tmp('sterling-cut-root-');
  mkdirSync(join(root, 'templates'));
  for (const t of ['launcher-tmux.sh', 'update-win.bat']) copyFileSync(join(REPO, 'templates', t), join(root, 'templates', t));
  if (git) mkdirSync(join(root, '.git'));
  return root;
}

/** A directory that looks like a Sterling clone (.git + plugin.json named sterling). */
function fakeClone() {
  const d = tmp('sterling-cut-clone-');
  mkdirSync(join(d, '.git'));
  mkdirSync(join(d, '.claude-plugin'));
  writeFileSync(join(d, '.claude-plugin', 'plugin.json'), JSON.stringify({ name: 'sterling', version: '0.18.0' }));
  return d;
}

// Modeled on a real 0.18.0 consumer launcher (Dome Farmer's sterling-launch.sh): the
// generated-paths block names the clone in PLUGIN_DIR and the TUI in the retired
// packages/tui/bundle location; claude starts with --plugin-dir "$PLUGIN_DIR".
const oldLauncher = (clone) => `#!/usr/bin/env bash
# Sterling tmux launcher (spec section 11) - GENERATED by /sterling:init
set -euo pipefail

MODE="\${1:-up}"
SESSION="sterling-dome-farmer"   # per-project: multiple projects at once, never one twice

# --- generated paths (machine-detected by init) ---
PLUGIN_DIR="${clone}"
TUI_BUNDLE="${clone}/packages/tui/bundle/sterling-tui.mjs"
SPLIT_RATIO=35   # right-pane width, percent

if [ "$MODE" = "up" ]; then
    tmux new-session -d -s "$SESSION" -c "$WORKDIR" "$CLAUDE_BIN" --plugin-dir "$PLUGIN_DIR"
fi
`;

// Modeled on the same project's sterling-update.bat (0.18.0: stamped, CRLF, cds into the
// clone's Windows path and runs scripts/update-console.sh there).
const oldUpdateBat = (winClone) => crlf(`@echo off
rem sterling-generated content_hash=7883d53923df58e597e1153c64018efef0b472cd8bd9e9be05462a52adeb1207
rem Sterling updater, WSL CHAIN - double-click from Explorer to bring this machine's
rem Sterling clone to origin's default branch.
"%LOCALAPPDATA%\\Microsoft\\WindowsApps\\wt.exe" wsl.exe --cd "${winClone}" -- bash -lic "bash scripts/update-console.sh"
`);

// ---- (1) the old-clone launcher marker ----

test('cloneLauncherTarget: the real 0.18.0 consumer shape qualifies by its generated header, and PLUGIN_DIR names the clone', () => {
  // the path does not exist here, so the header is the only signal that can answer
  assert.deepEqual(cloneLauncherTarget(oldLauncher('/nonexistent/sterling-main')), { clonePath: '/nonexistent/sterling-main', signal: 'generated-header' });
});

test('cloneLauncherTarget: a CRLF launcher is read the same, with no \\r in the clone path', () => {
  assert.deepEqual(cloneLauncherTarget(crlf(oldLauncher('/nonexistent/sterling-main'))), { clonePath: '/nonexistent/sterling-main', signal: 'generated-header' });
});

test('cloneLauncherTarget: today\'s authoring render is a clone launcher; the installed render is not', () => {
  const clone = pluginRoot({ git: true });
  const installed = pluginRoot({ git: false });
  const opts = { session: 'sterling-x', splitPercent: 35 };
  assert.deepEqual(cloneLauncherTarget(renderTmuxLauncher(clone, opts)), { clonePath: clone, signal: 'generated-header' });
  assert.equal(cloneLauncherTarget(renderTmuxLauncher(installed, opts)), null);
});

test('cloneLauncherTarget: no --plugin-dir, one in a full-line comment, or one in a trailing comment is not a clone launcher', () => {
  const header = '#!/usr/bin/env bash\n# GENERATED by /sterling:init\n';
  assert.equal(cloneLauncherTarget(`${header}exec claude\n`), null);
  assert.equal(cloneLauncherTarget(`${header}# we used to pass --plugin-dir here\nPLUGIN_DIR="/x"\nexec claude\n`), null);
  assert.equal(cloneLauncherTarget(`${header}PLUGIN_DIR="/x"\nexec claude   # was: --plugin-dir "$PLUGIN_DIR"\n`), null);
});

test('cloneLauncherTarget: with no generated header, a --plugin-dir at a Sterling clone qualifies by the clone on disk', () => {
  const clone = fakeClone();
  assert.deepEqual(cloneLauncherTarget(`exec claude --plugin-dir "${clone}"\n`), { clonePath: clone, signal: 'sterling-clone' });
  assert.deepEqual(cloneLauncherTarget(`exec claude --plugin-dir ${clone}\n`), { clonePath: clone, signal: 'sterling-clone' });
  assert.deepEqual(cloneLauncherTarget(`PLUGIN_DIR="${clone}"\nexec claude --plugin-dir "$PLUGIN_DIR"\n`), { clonePath: clone, signal: 'sterling-clone' });
});

test('cloneLauncherTarget: a launcher for the user\'s own plugin (no header, not a Sterling clone) is not a clone launcher', () => {
  const other = tmp('sterling-cut-otherplugin-');
  mkdirSync(join(other, '.git'));
  mkdirSync(join(other, '.claude-plugin'));
  writeFileSync(join(other, '.claude-plugin', 'plugin.json'), JSON.stringify({ name: 'my-plugin' }));
  assert.equal(cloneLauncherTarget(`exec claude --plugin-dir "${other}"\n`), null, 'another plugin\'s clone');
  assert.equal(cloneLauncherTarget('exec claude --plugin-dir ~/my-plugin\n'), null, 'a path that is not on disk as given');
  assert.equal(cloneLauncherTarget('exec claude --plugin-dir "$SOMEWHERE"\n'), null, 'an unresolved variable with no header');
  assert.deepEqual(cloneLauncherTarget('# GENERATED by /sterling:init\nexec claude --plugin-dir "$SOMEWHERE"\n'), { clonePath: null, signal: 'generated-header' }, 'the header alone qualifies, path unknown');
});

// ---- (2) sterling-update.bat on an installed copy ----

test('cloneUpdateLauncherTarget: the generated shape names its clone (Windows drvfs and POSIX forms); anything else is null', () => {
  assert.equal(cloneUpdateLauncherTarget(oldUpdateBat('C:\\Users\\chulf\\sterling-main')), '/mnt/c/Users/chulf/sterling-main');
  const clone = pluginRoot({ git: true });
  assert.equal(cloneUpdateLauncherTarget(renderUpdateLauncher(clone)), clone, 'an ext4 clone renders its POSIX path, which passes through');
  assert.equal(cloneUpdateLauncherTarget(`${oldUpdateBat('C:\\x')}del /q C:\\important\r\n`), null, 'an extra command line is not the generated shape');
  assert.equal(cloneUpdateLauncherTarget('@echo off\r\necho hello\r\n'), null);
  assert.equal(cloneUpdateLauncherTarget(oldUpdateBat('relative\\dir')), null, 'a cd target that is neither a drive path nor absolute POSIX is not recognised');
});

test('ensureUpdateLauncher on an installed copy: a generated clone updater is deleted and reported with its clone path', () => {
  const root = pluginRoot({ git: false });
  const target = tmp('sterling-cut-target-');
  writeFileSync(join(target, UPDATE_LAUNCHER_NAME), oldUpdateBat('C:\\Users\\chulf\\sterling-main'));
  const r = ensureUpdateLauncher(target, root);
  assert.equal(r.status, 'removed');
  assert.equal(r.clonePath, '/mnt/c/Users/chulf/sterling-main');
  assert.match(r.detail, /\/mnt\/c\/Users\/chulf\/sterling-main/);
  assert.ok(!existsSync(join(target, UPDATE_LAUNCHER_NAME)), 'the file is gone');
  assert.ok(!existsSync(join(target, '.gitignore')), 'nothing else is written');
});

test('ensureUpdateLauncher on an installed copy: an unrecognised sterling-update.bat is left byte-identical with a notice', () => {
  const root = pluginRoot({ git: false });
  const target = tmp('sterling-cut-target-');
  const body = '@echo off\r\nrem my own updater\r\ncall C:\\tools\\update-everything.bat\r\n';
  writeFileSync(join(target, UPDATE_LAUNCHER_NAME), body);
  const r = ensureUpdateLauncher(target, root);
  assert.equal(r.status, 'differs');
  assert.equal(r.clonePath, undefined);
  assert.match(r.detail, /left untouched/);
  assert.equal(readFileSync(join(target, UPDATE_LAUNCHER_NAME), 'utf8'), body);
});

test('ensureUpdateLauncher on an authoring clone: the old updater follows the ordinary refresh rules, never deletion', () => {
  const root = pluginRoot({ git: true });
  const target = tmp('sterling-cut-target-');
  writeFileSync(join(target, UPDATE_LAUNCHER_NAME), oldUpdateBat('C:\\Users\\chulf\\sterling-main'));
  const r = ensureUpdateLauncher(target, root);
  assert.notEqual(r.status, 'removed');
  assert.ok(existsSync(join(target, UPDATE_LAUNCHER_NAME)));
});

// ---- (3) the marketplace auto-update check ----

function configDir(settings) {
  const d = tmp('sterling-cut-cfg-');
  if (settings !== undefined) writeFileSync(join(d, 'settings.json'), typeof settings === 'string' ? settings : JSON.stringify(settings));
  return d;
}

test('marketplaceAutoUpdate reads <CLAUDE_CONFIG_DIR>/settings.json, else <home>/.claude/settings.json', () => {
  const cfg = configDir({ extraKnownMarketplaces: { sterling: { autoUpdate: true } } });
  assert.deepEqual(marketplaceAutoUpdate({ env: { CLAUDE_CONFIG_DIR: cfg } }), { path: join(cfg, 'settings.json'), enabled: true, entry: { autoUpdate: true } });
  const home = tmp('sterling-cut-home-');
  mkdirSync(join(home, '.claude'));
  writeFileSync(join(home, '.claude', 'settings.json'), '{}');
  const r = marketplaceAutoUpdate({ env: {}, home });
  assert.equal(r.path, join(home, '.claude', 'settings.json'));
  assert.equal(r.enabled, false);
  assert.equal(autoUpdateWarning(marketplaceAutoUpdate({ env: { CLAUDE_CONFIG_DIR: cfg } })), null, 'auto-update on: no warning');
});

test('autoUpdateWarning: an entry without autoUpdate gets that entry back with "autoUpdate": true, as exact JSON', () => {
  const entry = { source: { source: 'github', repo: 'Chulf58/sterling' } };
  const cfg = configDir({ extraKnownMarketplaces: { sterling: entry }, enabledPlugins: { 'sterling@sterling': true } });
  const line = autoUpdateWarning(marketplaceAutoUpdate({ env: { CLAUDE_CONFIG_DIR: cfg } }));
  assert.ok(line.includes(join(cfg, 'settings.json')), line);
  assert.ok(line.includes(JSON.stringify({ sterling: { ...entry, autoUpdate: true } })), line);
  const off = configDir({ extraKnownMarketplaces: { sterling: { ...entry, autoUpdate: false } } });
  assert.ok(autoUpdateWarning(marketplaceAutoUpdate({ env: { CLAUDE_CONFIG_DIR: off } })).includes('"autoUpdate":true'), 'false is not on');
});

test('autoUpdateWarning: no sterling entry, a missing file and an unparseable file each warn and never throw', () => {
  const none = autoUpdateWarning(marketplaceAutoUpdate({ env: { CLAUDE_CONFIG_DIR: configDir({}) } }));
  assert.match(none, /no extraKnownMarketplaces\.sterling entry/);
  assert.match(none, /"autoUpdate": true/);
  const missing = autoUpdateWarning(marketplaceAutoUpdate({ env: { CLAUDE_CONFIG_DIR: configDir() } }));
  assert.match(missing, /does not exist/);
  const broken = autoUpdateWarning(marketplaceAutoUpdate({ env: { CLAUDE_CONFIG_DIR: configDir('{ not json') } }));
  assert.match(broken, /could not be read: not valid JSON/);
});

test('autoUpdateWarning: every form says what settings.json lacks and that a /plugin toggle already switched on makes it ignorable', () => {
  const entry = { source: { source: 'github', repo: 'Chulf58/sterling' } };
  for (const cfg of [configDir({ extraKnownMarketplaces: { sterling: entry } }), configDir({}), configDir(), configDir('{ not json')]) {
    const line = autoUpdateWarning(marketplaceAutoUpdate({ env: { CLAUDE_CONFIG_DIR: cfg } }));
    assert.match(line, /"autoUpdate": true is not set for the sterling marketplace in settings\.json/, line);
    assert.match(line, /If you already switched auto-update on in \/plugin -> Marketplaces, ignore this warning/, line);
    assert.doesNotMatch(line, /does not update itself/, 'never claims auto-update is off: the toggle setting is not read');
  }
});

// ---- (4) the manual clone-deletion step ----

test('cloneCleanupLines: a Sterling clone is named for manual deletion; a path that is gone or not a clone says so', () => {
  const clone = fakeClone();
  const lines = cloneCleanupLines([clone, clone, '/nonexistent/sterling-old']).join('\n');
  assert.equal(lines.split('\n').filter((l) => l.includes(clone)).length, 1, 'each clone gets one line');
  assert.match(lines, /delete it by hand/);
  assert.match(lines, /\/nonexistent\/sterling-old.*not a Sterling clone on this machine/);
  assert.deepEqual(cloneCleanupLines([]), []);
});

test('cloneCleanupLines: a clone whose own config declares machine_role authoring is never offered for deletion', () => {
  const clone = fakeClone();
  mkdirSync(join(clone, '.sterling'));
  writeFileSync(join(clone, '.sterling', 'config.json'), JSON.stringify({ machine_role: 'authoring' }));
  const lines = cloneCleanupLines([clone]).join('\n');
  assert.match(lines, /authoring clone .*keep it/);
  assert.doesNotMatch(lines, /rm -rf|delete it by hand/);
});

test('cloneCleanupLines: a read failure other than ENOENT is printed as "could not inspect", never thrown', () => {
  const clone = fakeClone();
  mkdirSync(join(clone, '.sterling', 'config.json'), { recursive: true }); // a directory: reading it is EISDIR
  let lines;
  assert.doesNotThrow(() => { lines = cloneCleanupLines([clone]).join('\n'); });
  assert.ok(lines.includes(`could not inspect ${clone}: EISDIR`), lines);
  assert.doesNotMatch(lines, /rm -rf|delete it by hand/);
});

test('cloneCleanupLines: paths differing only by a trailing slash are one clone', () => {
  const clone = fakeClone();
  const lines = cloneCleanupLines([clone, `${clone}/`, `${clone}//`]);
  assert.equal(lines.filter((l) => l.includes(clone)).length, 1, lines.join('\n'));
  assert.ok(!lines.join('\n').includes(`${clone}/ `), 'the printed path carries no trailing slash');
});

// ---- end to end: init.mjs from an installed copy, and from the authoring clone ----
//
// The plugin root is THIS checkout. It counts as an installed copy when it resolves
// under <CLAUDE_CONFIG_DIR>/plugins/cache (isInstalledCopy's second signal), so a
// config dir whose plugins/cache symlinks to this checkout's parent makes the real
// init run the installed branch with no copy of the tree.
function installedConfigDir(settings) {
  const cfg = configDir(settings);
  mkdirSync(join(cfg, 'plugins'));
  symlinkSync(dirname(realpathSync(REPO)), join(cfg, 'plugins', 'cache'));
  return cfg;
}

function runInit(target, claudeConfigDir) {
  const r = spawnSync(process.execPath, [join(REPO, 'scripts', 'init.mjs'), '--target', target,
    '--project-name', 'cut-target', '--stack-tags', 'node', '--domain-description', 'node=test domain node', '--toolchain', 'node:**/*.mjs', '--backup-path', 'backups'], {
    encoding: 'utf8',
    cwd: target,
    timeout: 180_000,
    env: {
      ...process.env,
      HOME: tmp('sterling-cut-home-'), // init creates the declared domain stores under HOME
      STERLING_REGISTRY_DB: join(target, 'registry.db'),
      STERLING_PLUGIN_ROOT_MATCH: tmp('sterling-cut-prm-'),
      STERLING_CODEX_PROBE: 'absent',
      STERLING_CLAUDE_PROBE: 'ok',
      CLAUDE_CONFIG_DIR: claudeConfigDir,
    },
  });
  return { code: r.status, out: (r.stdout ?? '') + (r.stderr ?? '') };
}
const row = (out, item) => out.split('\n').find((l) => l.startsWith(item + ' ')) ?? '';

test('init from an installed copy: replaces the clone launcher, deletes the clone updater, warns on auto-update, names the clone for manual deletion', () => {
  const clone = fakeClone();
  const target = tmp('sterling-cut-project-');
  writeFileSync(join(target, 'sterling-launch.sh'), oldLauncher(clone));
  writeFileSync(join(target, UPDATE_LAUNCHER_NAME), oldUpdateBat(clone));
  const cfg = installedConfigDir({ extraKnownMarketplaces: { sterling: { source: { source: 'github', repo: 'Chulf58/sterling' } } } });

  const { code, out } = runInit(target, cfg);
  assert.equal(code, 0, out);

  const launcher = readFileSync(join(target, 'sterling-launch.sh'), 'utf8');
  assert.doesNotMatch(launcher, /--plugin-dir/, 'the launcher no longer overrides the installed plugin');
  assert.match(launcher, /newestInstalledSterling\(\)/, 'it is the installed shape');
  assert.match(row(out, 'sterling-launch.sh'), /replaced/);
  assert.ok(row(out, 'sterling-launch.sh').includes(clone), 'the replaced row names the old clone');

  assert.ok(!existsSync(join(target, UPDATE_LAUNCHER_NAME)), 'the clone updater is deleted');
  assert.match(row(out, UPDATE_LAUNCHER_NAME), /removed/);

  assert.ok(out.includes('"autoUpdate":true'), `the auto-update warning carries the JSON: ${out}`);

  const tail = out.slice(out.lastIndexOf('old Sterling clone'));
  assert.ok(tail.includes(clone), `the end of the run names the clone to delete: ${out}`);
  assert.ok(existsSync(join(clone, '.git')), 'the clone itself is never deleted');
});

test('init from an installed copy: a differing launcher without --plugin-dir is left alone; auto-update on prints no warning and no clone step', () => {
  const target = tmp('sterling-cut-project-');
  const own = '#!/usr/bin/env bash\n# my own launcher\nexec claude\n';
  writeFileSync(join(target, 'sterling-launch.sh'), own);
  const cfg = installedConfigDir({ extraKnownMarketplaces: { sterling: { autoUpdate: true } } });

  const { code, out } = runInit(target, cfg);
  assert.equal(code, 0, out);
  assert.equal(readFileSync(join(target, 'sterling-launch.sh'), 'utf8'), own);
  assert.match(row(out, 'sterling-launch.sh'), /differs/);
  assert.doesNotMatch(out, /autoUpdate/);
  assert.doesNotMatch(out, /old Sterling clone/);
});

test('init from an installed copy: a launcher passing --plugin-dir for the user\'s own plugin is left byte-identical as differs, with no clone step', () => {
  const target = tmp('sterling-cut-project-');
  const own = '#!/usr/bin/env bash\n# my launcher, with my own plugin\nexec claude --plugin-dir ~/my-plugin\n';
  writeFileSync(join(target, 'sterling-launch.sh'), own);
  const cfg = installedConfigDir({ extraKnownMarketplaces: { sterling: { autoUpdate: true } } });

  const { code, out } = runInit(target, cfg);
  assert.equal(code, 0, out);
  assert.equal(readFileSync(join(target, 'sterling-launch.sh'), 'utf8'), own);
  assert.match(row(out, 'sterling-launch.sh'), /differs/);
  assert.doesNotMatch(out, /old Sterling clone/);
});

test('init from the authoring clone: a clone launcher and a clone updater are not touched by the cutover, and nothing about auto-update is said', () => {
  const clone = fakeClone();
  const target = tmp('sterling-cut-project-');
  const launcherBody = oldLauncher(clone);
  writeFileSync(join(target, 'sterling-launch.sh'), launcherBody);
  writeFileSync(join(target, UPDATE_LAUNCHER_NAME), oldUpdateBat(clone));

  const { code, out } = runInit(target, configDir({}));
  assert.equal(code, 0, out);
  assert.equal(readFileSync(join(target, 'sterling-launch.sh'), 'utf8'), launcherBody, 'a clone keeps today\'s leave-alone behaviour');
  assert.match(row(out, 'sterling-launch.sh'), /differs/);
  assert.ok(existsSync(join(target, UPDATE_LAUNCHER_NAME)), 'the updater is never deleted on a clone');
  assert.doesNotMatch(out, /autoUpdate/);
  assert.doesNotMatch(out, /old Sterling clone/);
});
