// S6 consumer cutover (decision s6-consumer-cutover-init-on-installed-copy-fixes-launchers):
// /sterling:init run from an INSTALLED plugin copy moves a consumer project off its old
// clone. (1) a sterling-launch.sh that starts claude with --plugin-dir is replaced with
// the installed shape; (2) a sterling-update.bat in the generated clone-updater shape is
// deleted, anything else is left with a notice; (3) the sterling marketplace's auto-update
// is switched on in the user's settings.json; (4) the old clone is
// named for the user to delete by hand, never deleted. On an authoring clone nothing of
// this runs.
import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, copyFileSync, symlinkSync, realpathSync, readdirSync, lstatSync, statSync, chmodSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderTmuxLauncher } from '../lib/launcher-tmux.mjs';
import { ensureUpdateLauncher, renderUpdateLauncher, cloneUpdateLauncherTarget, UPDATE_LAUNCHER_NAME } from '../lib/update-launcher.mjs';
import { cloneLauncherTarget, enableMarketplaceAutoUpdate, cloneCleanupLines } from '../lib/consumer-cutover.mjs';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const made = new Set();
const tmp = (p) => { const d = mkdtempSync(join(tmpdir(), p)); made.add(d); return d; };
after(() => { for (const d of made) rmSync(d, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 }); });
const fwd = (p) => p.replace(/\\/g, '/');
const crlf = (s) => s.replace(/\r?\n/g, '\r\n');

/** A plugin root carrying the real templates; `git` decides authoring vs installed. */
function pluginRoot({ git }) {
  const root = tmp('sterling-cut-root-');
  mkdirSync(join(root, 'templates'));
  for (const t of ['launcher-tmux.sh', 'update-win.bat']) copyFileSync(join(REPO, 'templates', t), join(root, 'templates', t));
  if (git) mkdirSync(join(root, '.git'));
  return root;
}

/** A directory that looks like a Sterling clone (.git + plugin.json named sterling). */
function fakeClone() {
  const d = tmp('sterling-cut-clone-');
  mkdirSync(join(d, '.git'));
  mkdirSync(join(d, '.claude-plugin'));
  writeFileSync(join(d, '.claude-plugin', 'plugin.json'), JSON.stringify({ name: 'sterling', version: '0.18.0' }));
  return d;
}

// Modeled on a real 0.18.0 consumer launcher (Dome Farmer's sterling-launch.sh): the
// generated-paths block names the clone in PLUGIN_DIR and the TUI in the retired
// packages/tui/bundle location; claude starts with --plugin-dir "$PLUGIN_DIR".
const oldLauncher = (clone) => `#!/usr/bin/env bash
# Sterling tmux launcher (spec section 11) - GENERATED by /sterling:init
set -euo pipefail

MODE="\${1:-up}"
SESSION="sterling-dome-farmer"   # per-project: multiple projects at once, never one twice

# --- generated paths (machine-detected by init) ---
PLUGIN_DIR="${clone}"
TUI_BUNDLE="${clone}/packages/tui/bundle/sterling-tui.mjs"
SPLIT_RATIO=35   # right-pane width, percent

if [ "$MODE" = "up" ]; then
    tmux new-session -d -s "$SESSION" -c "$WORKDIR" "$CLAUDE_BIN" --plugin-dir "$PLUGIN_DIR"
fi
`;

// Modeled on the same project's sterling-update.bat (0.18.0: stamped, CRLF, cds into the
// clone's Windows path and runs scripts/update-console.sh there).
const oldUpdateBat = (winClone) => crlf(`@echo off
rem sterling-generated content_hash=7883d53923df58e597e1153c64018efef0b472cd8bd9e9be05462a52adeb1207
rem Sterling updater, WSL CHAIN - double-click from Explorer to bring this machine's
rem Sterling clone to origin's default branch.
"%LOCALAPPDATA%\\Microsoft\\WindowsApps\\wt.exe" wsl.exe --cd "${winClone}" -- bash -lic "bash scripts/update-console.sh"
`);

// ---- (1) the old-clone launcher marker ----

test('cloneLauncherTarget: the real 0.18.0 consumer shape qualifies by its generated header, and PLUGIN_DIR names the clone', () => {
  // the path does not exist here, so the header is the only signal that can answer
  assert.deepEqual(cloneLauncherTarget(oldLauncher('/nonexistent/sterling-main')), { clonePath: '/nonexistent/sterling-main', signal: 'generated-header' });
});

test('cloneLauncherTarget: a CRLF launcher is read the same, with no \\r in the clone path', () => {
  assert.deepEqual(cloneLauncherTarget(crlf(oldLauncher('/nonexistent/sterling-main'))), { clonePath: '/nonexistent/sterling-main', signal: 'generated-header' });
});

test('cloneLauncherTarget: today\'s authoring render is a clone launcher; the installed render is not', () => {
  const clone = pluginRoot({ git: true });
  const installed = pluginRoot({ git: false });
  const opts = { session: 'sterling-x', splitPercent: 35 };
  assert.deepEqual(cloneLauncherTarget(renderTmuxLauncher(clone, opts)), { clonePath: clone, signal: 'generated-header' });
  assert.equal(cloneLauncherTarget(renderTmuxLauncher(installed, opts)), null);
});

test('cloneLauncherTarget: no --plugin-dir, one in a full-line comment, or one in a trailing comment is not a clone launcher', () => {
  const header = '#!/usr/bin/env bash\n# GENERATED by /sterling:init\n';
  assert.equal(cloneLauncherTarget(`${header}exec claude\n`), null);
  assert.equal(cloneLauncherTarget(`${header}# we used to pass --plugin-dir here\nPLUGIN_DIR="/x"\nexec claude\n`), null);
  assert.equal(cloneLauncherTarget(`${header}PLUGIN_DIR="/x"\nexec claude   # was: --plugin-dir "$PLUGIN_DIR"\n`), null);
});

test('cloneLauncherTarget: with no generated header, a --plugin-dir at a Sterling clone qualifies by the clone on disk', () => {
  const clone = fakeClone();
  assert.deepEqual(cloneLauncherTarget(`exec claude --plugin-dir "${clone}"\n`), { clonePath: clone, signal: 'sterling-clone' });
  assert.deepEqual(cloneLauncherTarget(`exec claude --plugin-dir ${clone}\n`), { clonePath: clone, signal: 'sterling-clone' });
  assert.deepEqual(cloneLauncherTarget(`PLUGIN_DIR="${clone}"\nexec claude --plugin-dir "$PLUGIN_DIR"\n`), { clonePath: clone, signal: 'sterling-clone' });
});

test('cloneLauncherTarget: a launcher for the user\'s own plugin (no header, not a Sterling clone) is not a clone launcher', () => {
  const other = tmp('sterling-cut-otherplugin-');
  mkdirSync(join(other, '.git'));
  mkdirSync(join(other, '.claude-plugin'));
  writeFileSync(join(other, '.claude-plugin', 'plugin.json'), JSON.stringify({ name: 'my-plugin' }));
  assert.equal(cloneLauncherTarget(`exec claude --plugin-dir "${other}"\n`), null, 'another plugin\'s clone');
  assert.equal(cloneLauncherTarget('exec claude --plugin-dir ~/my-plugin\n'), null, 'a path that is not on disk as given');
  assert.equal(cloneLauncherTarget('exec claude --plugin-dir "$SOMEWHERE"\n'), null, 'an unresolved variable with no header');
  assert.deepEqual(cloneLauncherTarget('# GENERATED by /sterling:init\nexec claude --plugin-dir "$SOMEWHERE"\n'), { clonePath: null, signal: 'generated-header' }, 'the header alone qualifies, path unknown');
});

// ---- (2) sterling-update.bat on an installed copy ----

test('cloneUpdateLauncherTarget: the generated shape names its clone (Windows drvfs and POSIX forms); anything else is null', () => {
  assert.equal(cloneUpdateLauncherTarget(oldUpdateBat('C:\\Users\\chulf\\sterling-main')), '/mnt/c/Users/chulf/sterling-main');
  const clone = pluginRoot({ git: true });
  assert.equal(cloneUpdateLauncherTarget(renderUpdateLauncher(clone)), clone, 'an ext4 clone renders its POSIX path, which passes through');
  assert.equal(cloneUpdateLauncherTarget(`${oldUpdateBat('C:\\x')}del /q C:\\important\r\n`), null, 'an extra command line is not the generated shape');
  assert.equal(cloneUpdateLauncherTarget('@echo off\r\necho hello\r\n'), null);
  assert.equal(cloneUpdateLauncherTarget(oldUpdateBat('relative\\dir')), null, 'a cd target that is neither a drive path nor absolute POSIX is not recognised');
});

test('ensureUpdateLauncher on an installed copy: a generated clone updater is deleted and reported with its clone path', () => {
  const root = pluginRoot({ git: false });
  const target = tmp('sterling-cut-target-');
  writeFileSync(join(target, UPDATE_LAUNCHER_NAME), oldUpdateBat('C:\\Users\\chulf\\sterling-main'));
  const r = ensureUpdateLauncher(target, root);
  assert.equal(r.status, 'removed');
  assert.equal(r.clonePath, '/mnt/c/Users/chulf/sterling-main');
  assert.match(r.detail, /\/mnt\/c\/Users\/chulf\/sterling-main/);
  assert.ok(!existsSync(join(target, UPDATE_LAUNCHER_NAME)), 'the file is gone');
  assert.ok(!existsSync(join(target, '.gitignore')), 'nothing else is written');
});

test('ensureUpdateLauncher on an installed copy: an unrecognised sterling-update.bat is left byte-identical with a notice', () => {
  const root = pluginRoot({ git: false });
  const target = tmp('sterling-cut-target-');
  const body = '@echo off\r\nrem my own updater\r\ncall C:\\tools\\update-everything.bat\r\n';
  writeFileSync(join(target, UPDATE_LAUNCHER_NAME), body);
  const r = ensureUpdateLauncher(target, root);
  assert.equal(r.status, 'differs');
  assert.equal(r.clonePath, undefined);
  assert.match(r.detail, /left untouched/);
  assert.equal(readFileSync(join(target, UPDATE_LAUNCHER_NAME), 'utf8'), body);
});

test('ensureUpdateLauncher on an authoring clone: the old updater follows the ordinary refresh rules, never deletion', () => {
  const root = pluginRoot({ git: true });
  const target = tmp('sterling-cut-target-');
  writeFileSync(join(target, UPDATE_LAUNCHER_NAME), oldUpdateBat('C:\\Users\\chulf\\sterling-main'));
  const r = ensureUpdateLauncher(target, root);
  assert.notEqual(r.status, 'removed');
  assert.ok(existsSync(join(target, UPDATE_LAUNCHER_NAME)));
});

// ---- (3) the marketplace auto-update switch ----
//
// Claude Code decides per marketplace: the extraKnownMarketplaces.<name>.autoUpdate in a
// settings file first, else autoUpdate on the known_marketplaces.json entry (the /plugin
// toggle writes it), else the default, which is off for sterling
// (https://code.claude.com/docs/en/plugins/loading, "Which marketplaces and plugins
// auto-update", read 2026-10-06). Init turns it on in the user's settings.json.

const SRC = { source: 'github', repo: 'Chulf58/sterling' };

/** A Claude config dir: settings.json and plugins/known_marketplaces.json, each given as an object, a raw string, or undefined for "no file". */
function configDir(settings, known) {
  const d = tmp('sterling-cut-cfg-');
  const put = (path, v) => { if (v !== undefined) writeFileSync(path, typeof v === 'string' ? v : JSON.stringify(v)); };
  put(join(d, 'settings.json'), settings);
  if (known !== undefined) {
    mkdirSync(join(d, 'plugins'));
    put(join(d, 'plugins', 'known_marketplaces.json'), known);
  }
  return d;
}
const settingsOf = (cfg) => join(cfg, 'settings.json');
const readSettings = (cfg) => JSON.parse(readFileSync(settingsOf(cfg), 'utf8'));
const run = (cfg, extra = {}) => enableMarketplaceAutoUpdate({ env: { CLAUDE_CONFIG_DIR: cfg }, ...extra });

test('enableMarketplaceAutoUpdate reads <CLAUDE_CONFIG_DIR>/settings.json, else <home>/.claude/settings.json', () => {
  const cfg = configDir({ extraKnownMarketplaces: { sterling: { source: SRC, autoUpdate: true } } });
  assert.deepEqual(run(cfg), { status: 'already-on', path: settingsOf(cfg), line: null });
  const home = tmp('sterling-cut-home-');
  mkdirSync(join(home, '.claude'));
  writeFileSync(join(home, '.claude', 'settings.json'), JSON.stringify({ extraKnownMarketplaces: { sterling: { source: SRC } } }));
  mkdirSync(join(home, '.claude', 'plugins'));
  writeFileSync(join(home, '.claude', 'plugins', 'known_marketplaces.json'), '{}');
  const r = enableMarketplaceAutoUpdate({ env: {}, home });
  assert.equal(r.status, 'written');
  assert.equal(r.path, join(home, '.claude', 'settings.json'));
  assert.equal(JSON.parse(readFileSync(r.path, 'utf8')).extraKnownMarketplaces.sterling.autoUpdate, true);
});

test('2a: a settings entry without autoUpdate gets autoUpdate: true, its source and every other key keep their meaning, one line names file, key and next session', () => {
  const settings = {
    model: 'opus',
    permissions: { allow: ['Bash(git status)'], deny: [] },
    enabledPlugins: { 'sterling@sterling': true },
    extraKnownMarketplaces: { other: { source: { source: 'github', repo: 'a/b' }, autoUpdate: false }, sterling: { source: SRC } },
  };
  const cfg = configDir(settings, {});
  const r = run(cfg);
  assert.equal(r.status, 'written');
  assert.equal(r.path, settingsOf(cfg));
  const after = readSettings(cfg);
  assert.deepEqual(after, { ...settings, extraKnownMarketplaces: { ...settings.extraKnownMarketplaces, sterling: { source: SRC, autoUpdate: true } } });
  assert.ok(!r.line.includes('\n'), 'one line');
  assert.ok(r.line.includes(fwd(settingsOf(cfg))), r.line);
  assert.match(r.line, /extraKnownMarketplaces\.sterling\.autoUpdate/);
  assert.match(r.line, /next session/);
  assert.deepEqual(readdirSync(cfg).sort(), ['plugins', 'settings.json'], 'no temp file left behind');
});

test('2a: a write keeps CRLF line endings and a missing trailing newline, and drops a leading BOM', () => {
  const body = JSON.stringify({ extraKnownMarketplaces: { sterling: { source: SRC } } }, null, 2).replace(/\n/g, '\r\n');
  const cfg = configDir('﻿' + body, {});
  assert.equal(run(cfg).status, 'written');
  const raw = readFileSync(settingsOf(cfg), 'utf8');
  assert.ok(!raw.startsWith('﻿'), 'the BOM is not written back');
  assert.ok(raw.includes('\r\n') && !/[^\r]\n/.test(raw), 'CRLF kept throughout');
  assert.ok(!raw.endsWith('\n'), 'no trailing newline was added');
  assert.equal(JSON.parse(raw).extraKnownMarketplaces.sterling.autoUpdate, true);
});

test('2b: no settings entry but known_marketplaces.json has sterling with a source: the settings entry is created with exactly that source, known_marketplaces.json is never written', () => {
  const known = { 'claude-plugins-official': { source: { source: 'github', repo: 'anthropics/claude-plugins-official' }, installLocation: '/x', lastUpdated: 't' }, sterling: { source: SRC, installLocation: '/y', lastUpdated: 't' } };
  const settings = { model: 'opus', extraKnownMarketplaces: { other: { source: { source: 'github', repo: 'a/b' } } } };
  const cfg = configDir(settings, known);
  const knownPath = join(cfg, 'plugins', 'known_marketplaces.json');
  const knownBefore = readFileSync(knownPath, 'utf8');
  const r = run(cfg);
  assert.equal(r.status, 'written');
  assert.deepEqual(readSettings(cfg), { model: 'opus', extraKnownMarketplaces: { other: settings.extraKnownMarketplaces.other, sterling: { source: SRC, autoUpdate: true } } });
  assert.equal(readFileSync(knownPath, 'utf8'), knownBefore, 'Claude Code\'s own state file is untouched');
  assert.match(r.line, /next session/);
});

test('2b: no extraKnownMarketplaces key at all is created whole, with only the known source', () => {
  const cfg = configDir({ model: 'opus' }, { sterling: { source: SRC } });
  assert.equal(run(cfg).status, 'written');
  assert.deepEqual(readSettings(cfg), { model: 'opus', extraKnownMarketplaces: { sterling: { source: SRC, autoUpdate: true } } });
});

test('2b: a known_marketplaces.json sterling entry with no source object writes nothing and says so', () => {
  for (const known of [{ sterling: { installLocation: '/y' } }, { sterling: { source: 'github' } }]) {
    const cfg = configDir({ model: 'opus' }, known);
    const r = run(cfg);
    assert.equal(r.status, 'no-source');
    assert.deepEqual(readSettings(cfg), { model: 'opus' });
    assert.match(r.line, /known_marketplaces\.json/);
  }
});

test('2c: neither file knows sterling: nothing is written and the line gives the /plugin steps', () => {
  for (const cfg of [configDir({ model: 'opus' }, {}), configDir({ model: 'opus' }, { other: { source: SRC } })]) {
    const before = readFileSync(settingsOf(cfg), 'utf8');
    const r = run(cfg);
    assert.equal(r.status, 'no-entry');
    assert.equal(readFileSync(settingsOf(cfg), 'utf8'), before);
    assert.match(r.line, /\/plugin/);
    assert.match(r.line, /Marketplaces/);
    assert.match(r.line, /Enable auto-update/);
  }
});

test('2d: an explicit autoUpdate: false in the settings entry is not flipped; one line says it is off by setting and how to turn it on', () => {
  const settings = { extraKnownMarketplaces: { sterling: { source: SRC, autoUpdate: false } } };
  const cfg = configDir(settings, { sterling: { source: SRC, autoUpdate: true } });
  const before = readFileSync(settingsOf(cfg), 'utf8');
  const r = run(cfg);
  assert.equal(r.status, 'explicit-off');
  assert.equal(readFileSync(settingsOf(cfg), 'utf8'), before);
  assert.ok(!r.line.includes('\n'), 'one line');
  assert.match(r.line, /off by an explicit setting/);
  assert.ok(r.line.includes(fwd(settingsOf(cfg))), r.line);
  assert.match(r.line, /autoUpdate": true/);
});

test('an explicit autoUpdate: false on the known_marketplaces.json entry (the /plugin toggle off) is a deliberate choice too: not overridden', () => {
  const cfg = configDir({ extraKnownMarketplaces: { sterling: { source: SRC } } }, { sterling: { source: SRC, autoUpdate: false } });
  const before = readFileSync(settingsOf(cfg), 'utf8');
  const r = run(cfg);
  assert.equal(r.status, 'explicit-off');
  assert.equal(readFileSync(settingsOf(cfg), 'utf8'), before);
  assert.match(r.line, /known_marketplaces\.json/);
});

test('already on through the settings entry: no write, no line; the known file is not even needed', () => {
  const cfg = configDir({ extraKnownMarketplaces: { sterling: { source: SRC, autoUpdate: true } } }, '{ not json');
  const before = readFileSync(settingsOf(cfg), 'utf8');
  assert.deepEqual(run(cfg), { status: 'already-on', path: settingsOf(cfg), line: null });
  assert.equal(readFileSync(settingsOf(cfg), 'utf8'), before);
});

test('already on through known_marketplaces.json only (the toggle was used, settings carries no autoUpdate): no write, no line', () => {
  for (const settings of [{ model: 'opus' }, { extraKnownMarketplaces: { sterling: { source: SRC } } }]) {
    const cfg = configDir(settings, { sterling: { source: SRC, autoUpdate: true } });
    const before = readFileSync(settingsOf(cfg), 'utf8');
    assert.deepEqual(run(cfg), { status: 'already-on', path: settingsOf(cfg), line: null });
    assert.equal(readFileSync(settingsOf(cfg), 'utf8'), before);
  }
});

test('the settings value outranks the known one: a settings autoUpdate: true is on even when known says false', () => {
  const cfg = configDir({ extraKnownMarketplaces: { sterling: { source: SRC, autoUpdate: true } } }, { sterling: { source: SRC, autoUpdate: false } });
  assert.equal(run(cfg).status, 'already-on');
});

test('a missing known_marketplaces.json writes nothing, with or without a settings entry: the line names that file and the manual step', () => {
  for (const settings of [{ extraKnownMarketplaces: { sterling: { source: SRC } } }, { model: 'opus' }]) {
    const cfg = configDir(settings);
    const before = readFileSync(settingsOf(cfg), 'utf8');
    const r = run(cfg);
    assert.equal(r.status, 'known-missing');
    assert.equal(readFileSync(settingsOf(cfg), 'utf8'), before, 'settings untouched');
    assert.deepEqual(readdirSync(cfg), ['settings.json'], 'nothing created');
    assert.ok(!r.line.includes('\n'), 'one line');
    assert.ok(r.line.includes(fwd(join(cfg, 'plugins', 'known_marketplaces.json'))), r.line);
    assert.match(r.line, /does not exist/);
    assert.match(r.line, /Enable auto-update/);
  }
});

// The write goes to the file the path really names, so a settings.json kept as a symlink
// (a dotfiles checkout) stays a link and its target gets the new content.
function linkedConfigDir(settings) {
  const cfg = configDir(undefined, {});
  const store = tmp('sterling-cut-dotfiles-');
  const target = join(store, 'claude-settings.json');
  if (settings !== undefined) writeFileSync(target, JSON.stringify(settings));
  symlinkSync(target, settingsOf(cfg));
  return { cfg, store, target };
}

test('a symlinked settings.json stays a symlink and its target gets the new content; no temp file is left in either directory', () => {
  const { cfg, store, target } = linkedConfigDir({ model: 'opus', extraKnownMarketplaces: { sterling: { source: SRC } } });
  const r = run(cfg);
  assert.equal(r.status, 'written');
  assert.ok(lstatSync(settingsOf(cfg)).isSymbolicLink(), 'the link is still a link');
  assert.ok(lstatSync(target).isFile(), 'the target is still a regular file');
  assert.deepEqual(JSON.parse(readFileSync(target, 'utf8')), { model: 'opus', extraKnownMarketplaces: { sterling: { source: SRC, autoUpdate: true } } });
  assert.deepEqual(readdirSync(store), ['claude-settings.json'], 'no temp file beside the target');
  assert.deepEqual(readdirSync(cfg).sort(), ['plugins', 'settings.json'], 'no temp file beside the link');
  assert.ok(r.line.includes(fwd(settingsOf(cfg))), r.line);
});

test('a write keeps the settings file\'s mode: a 0600 file stays 0600, directly and through a symlink', () => {
  const direct = configDir({ extraKnownMarketplaces: { sterling: { source: SRC } } }, {});
  chmodSync(settingsOf(direct), 0o600);
  assert.equal(run(direct).status, 'written');
  assert.equal(statSync(settingsOf(direct)).mode & 0o777, 0o600);

  const { cfg, target } = linkedConfigDir({ extraKnownMarketplaces: { sterling: { source: SRC } } });
  chmodSync(target, 0o640);
  assert.equal(run(cfg).status, 'written');
  assert.equal(statSync(target).mode & 0o777, 0o640);
});

test('a dangling settings.json symlink: nothing is written, the link is left as it is and its target is not created', () => {
  const { cfg, store, target } = linkedConfigDir(undefined);
  const r = run(cfg);
  assert.equal(r.status, 'settings-missing');
  assert.ok(lstatSync(settingsOf(cfg)).isSymbolicLink());
  assert.ok(!existsSync(target), 'the target is not created');
  assert.deepEqual(readdirSync(store), []);
  assert.match(r.line, /Enable auto-update/);

  // The same link, with the read answered from elsewhere: the real path still cannot be
  // resolved, so the write step itself refuses.
  const readFile = (p, enc) => (p === settingsOf(cfg) ? JSON.stringify({ extraKnownMarketplaces: { sterling: { source: SRC } } }) : readFileSync(p, enc));
  const second = run(cfg, { readFile });
  assert.equal(second.status, 'settings-unwritable');
  assert.ok(lstatSync(settingsOf(cfg)).isSymbolicLink(), 'the link is not replaced by a regular file');
  assert.ok(!existsSync(target), 'the target is not created');
  assert.deepEqual(readdirSync(store), []);
  assert.deepEqual(readdirSync(cfg).sort(), ['plugins', 'settings.json'], 'no temp file left behind');
  assert.ok(!second.line.includes('\n'), 'one line');
  assert.match(second.line, /ENOENT/);
  assert.match(second.line, /Enable auto-update/);
});

test('a failed write or rename is settings-unwritable: the file is byte-identical, no temp file is left, and the line carries only the error code', () => {
  const fail = (code) => () => { const e = new Error(`${code}: operation failed, open /secret/path\nline two`); e.code = code; throw e; };
  for (const [what, extra, code] of [['writeFile', { writeFile: fail('EACCES') }, 'EACCES'], ['rename', { rename: fail('EXDEV') }, 'EXDEV']]) {
    const cfg = configDir({ extraKnownMarketplaces: { sterling: { source: SRC } } }, {});
    const before = readFileSync(settingsOf(cfg), 'utf8');
    const r = run(cfg, extra);
    assert.equal(r.status, 'settings-unwritable', what);
    assert.equal(readFileSync(settingsOf(cfg), 'utf8'), before, `${what}: untouched`);
    assert.deepEqual(readdirSync(cfg).sort(), ['plugins', 'settings.json'], `${what}: no temp file left behind`);
    assert.ok(r.line.includes(code), r.line);
    assert.ok(!r.line.includes('operation failed') && !r.line.includes('/secret/path') && !r.line.includes('\n'), r.line);
    assert.ok(r.line.includes(fwd(settingsOf(cfg))), r.line);
    assert.match(r.line, /Enable auto-update/);
  }
});

test('a missing settings.json is not created: nothing is written and the line names the file and the manual step', () => {
  const cfg = configDir(undefined, { sterling: { source: SRC } });
  const r = run(cfg);
  assert.equal(r.status, 'settings-missing');
  assert.ok(!existsSync(settingsOf(cfg)), 'never created');
  assert.ok(r.line.includes(fwd(settingsOf(cfg))), r.line);
  assert.match(r.line, /Enable auto-update/);
});

test('a malformed settings.json is left byte-identical and the line is one line holding none of its content', () => {
  const secret = 'sk-ant-api03-DO-NOT-LEAK';
  const bodies = ['{ not json', `{\n  "env": { "KEY": "${secret}" },\n  "x": nope\n}\n`, '[1, 2]', 'null'];
  for (const body of bodies) {
    const cfg = configDir(body, { sterling: { source: SRC } });
    const r = run(cfg);
    assert.equal(r.status, 'settings-invalid', body);
    assert.equal(readFileSync(settingsOf(cfg), 'utf8'), body, 'untouched');
    assert.ok(!r.line.includes('\n'), `one line: ${r.line}`);
    assert.ok(!r.line.includes(secret) && !r.line.includes('nope'), `no file content in the notice: ${r.line}`);
    assert.ok(r.line.includes(fwd(settingsOf(cfg))), r.line);
    assert.match(r.line, /not valid JSON|not a JSON object/);
  }
});

test('a settings.json whose extraKnownMarketplaces or sterling entry is not an object is left untouched with a loud line', () => {
  for (const settings of [{ extraKnownMarketplaces: 'x' }, { extraKnownMarketplaces: [] }, { extraKnownMarketplaces: { sterling: 'github' } }]) {
    const cfg = configDir(settings, { sterling: { source: SRC } });
    const before = readFileSync(settingsOf(cfg), 'utf8');
    const r = run(cfg);
    assert.equal(r.status, 'settings-invalid');
    assert.equal(readFileSync(settingsOf(cfg), 'utf8'), before);
    assert.ok(!r.line.includes('\n'));
  }
});

test('an unreadable settings.json reports only the error code, never the message', () => {
  const cfg = configDir({});
  const readFile = () => { const e = new Error('EACCES: permission denied, open /secret/path\nline two'); e.code = 'EACCES'; throw e; };
  const r = run(cfg, { readFile });
  assert.equal(r.status, 'settings-unreadable');
  assert.match(r.line, /EACCES/);
  assert.ok(!r.line.includes('permission denied') && !r.line.includes('/secret/path') && !r.line.includes('\n'), r.line);
});

test('a malformed known_marketplaces.json: no write, the line names that file and holds none of its content', () => {
  const secret = 'ghp_DO-NOT-LEAK';
  for (const settings of [{ model: 'opus' }, { extraKnownMarketplaces: { sterling: { source: SRC } } }]) {
    const cfg = configDir(settings, `{\n  "sterling": { "token": "${secret}" },\n  "y": nope\n}`);
    const before = readFileSync(settingsOf(cfg), 'utf8');
    const r = run(cfg);
    assert.equal(r.status, 'known-invalid');
    assert.equal(readFileSync(settingsOf(cfg), 'utf8'), before, 'settings untouched');
    assert.ok(r.line.includes('known_marketplaces.json'), r.line);
    assert.ok(!r.line.includes(secret) && !r.line.includes('nope') && !r.line.includes('\n'), r.line);
  }
});

test('known_marketplaces.json is found under CLAUDE_CODE_PLUGIN_CACHE_DIR when that is set (the plugins root Claude Code documents)', () => {
  const cfg = configDir({ model: 'opus' });
  const root = tmp('sterling-cut-plugins-');
  writeFileSync(join(root, 'known_marketplaces.json'), JSON.stringify({ sterling: { source: SRC } }));
  const r = enableMarketplaceAutoUpdate({ env: { CLAUDE_CONFIG_DIR: cfg, CLAUDE_CODE_PLUGIN_CACHE_DIR: root } });
  assert.equal(r.status, 'written');
  assert.equal(readSettings(cfg).extraKnownMarketplaces.sterling.source.repo, 'Chulf58/sterling');
});

// ---- (4) the manual clone-deletion step ----

test('cloneCleanupLines: a Sterling clone is named for manual deletion; a path that is gone or not a clone says so', () => {
  const clone = fakeClone();
  const lines = cloneCleanupLines([clone, clone, '/nonexistent/sterling-old'], []).join('\n');
  assert.equal(lines.split('\n').filter((l) => l.includes(clone)).length, 1, 'each clone gets one line');
  assert.match(lines, /delete it by hand/);
  assert.match(lines, /\/nonexistent\/sterling-old.*not a Sterling clone on this machine/);
  assert.deepEqual(cloneCleanupLines([]), []);
});

test('cloneCleanupLines: a clone whose own config declares machine_role authoring is never offered for deletion', () => {
  const clone = fakeClone();
  mkdirSync(join(clone, '.sterling'));
  writeFileSync(join(clone, '.sterling', 'config.json'), JSON.stringify({ machine_role: 'authoring' }));
  const lines = cloneCleanupLines([clone], []).join('\n');
  assert.match(lines, /authoring clone .*keep it/);
  assert.doesNotMatch(lines, /rm -rf|delete it by hand/);
});

test('cloneCleanupLines: a read failure other than ENOENT is printed as "could not inspect", never thrown', () => {
  const clone = fakeClone();
  mkdirSync(join(clone, '.sterling', 'config.json'), { recursive: true }); // a directory: reading it is EISDIR
  let lines;
  assert.doesNotThrow(() => { lines = cloneCleanupLines([clone], []).join('\n'); });
  assert.ok(lines.includes(`could not inspect ${clone}: EISDIR`), lines);
  assert.doesNotMatch(lines, /rm -rf|delete it by hand/);
});

test('cloneCleanupLines: paths differing only by a trailing slash are one clone', () => {
  const clone = fakeClone();
  const lines = cloneCleanupLines([clone, `${clone}/`, `${clone}//`], []);
  assert.equal(lines.filter((l) => l.includes(clone)).length, 1, lines.join('\n'));
  assert.ok(!lines.join('\n').includes(`${clone}/ `), 'the printed path carries no trailing slash');
});

// ---- (4b) a live Sterling project is never offered for deletion ----
// The init target and every registered project hold a knowledge store and history;
// the clone paths come from launchers, so one of them can BE such a project (consumer
// reports #2 and #3: the hint printed rm -rf for the directory init was running in).

test('cloneCleanupLines: a clone that is the init target is a live project to keep, never rm -rf', () => {
  const clone = fakeClone();
  const lines = cloneCleanupLines([clone], [clone]).join('\n');
  assert.match(lines, /live Sterling project on this machine/);
  assert.match(lines, /its own store/);
  assert.match(lines, /keep it/);
  assert.match(lines, /Only the --plugin-dir launch was replaced/);
  assert.doesNotMatch(lines, /rm -rf|delete it by hand/);
});

test('cloneCleanupLines: a clone that is a registered project gets the keep line; an unregistered clone still gets the rm -rf hint', () => {
  const registered = fakeClone();
  const stray = fakeClone();
  const lines = cloneCleanupLines([registered, stray], [fakeClone(), registered]);
  const reg = lines.find((l) => l.includes(registered));
  const unreg = lines.find((l) => l.includes(stray));
  assert.match(reg, /live Sterling project/);
  assert.doesNotMatch(reg, /rm -rf|delete it by hand/);
  assert.match(unreg, /delete it by hand once no project on this machine launches from it \(rm -rf "/);
});

test('cloneCleanupLines: a live path matches across a trailing slash and backslashes, in either argument', () => {
  const clone = fakeClone();
  const back = clone.replace(/\//g, '\\');
  for (const [named, live] of [[clone, `${clone}/`], [clone, `${clone}//`], [clone, back], [back, clone]]) {
    const lines = cloneCleanupLines([named], [live]).join('\n');
    assert.match(lines, /live Sterling project/, `${named} vs ${live}`);
    assert.doesNotMatch(lines, /rm -rf/, `${named} vs ${live}`);
  }
});

test('cloneCleanupLines: an unreadable registry (null) treats every clone path as live and says so; never rm -rf', () => {
  const clone = fakeClone();
  const lines = cloneCleanupLines([clone, '/nonexistent/sterling-old'], null).join('\n');
  assert.match(lines, /project registry could not be read/);
  assert.ok(lines.includes(clone));
  assert.match(lines, /treated as a live project/);
  assert.doesNotMatch(lines, /rm -rf|delete it by hand/);
});

test('cloneCleanupLines: an omitted live-project list means unknown, not none: no rm -rf', () => {
  const clone = fakeClone();
  const lines = cloneCleanupLines([clone]).join('\n');
  assert.match(lines, /project registry could not be read/);
  assert.doesNotMatch(lines, /rm -rf|delete it by hand/);
});

test('cloneCleanupLines: a clone that CONTAINS a live project is kept; a clone inside a live project, or a name-prefix sibling, keeps the hint', () => {
  const clone = fakeClone();
  const nested = join(clone, 'projects', 'app');
  mkdirSync(nested, { recursive: true });
  const containing = cloneCleanupLines([clone], [nested]).join('\n');
  assert.match(containing, /contains a live Sterling project on this machine; keep it/);
  assert.doesNotMatch(containing, /rm -rf|delete it by hand/);

  const parent = tmp('sterling-cut-liveparent-');
  const inside = join(parent, 'clone');
  mkdirSync(join(inside, '.git'), { recursive: true });
  mkdirSync(join(inside, '.claude-plugin'));
  writeFileSync(join(inside, '.claude-plugin', 'plugin.json'), JSON.stringify({ name: 'sterling' }));
  assert.match(cloneCleanupLines([inside], [parent]).join('\n'), /rm -rf/, 'a clone inside a live project is still a clone to delete');

  assert.match(cloneCleanupLines([clone], [`${clone}2`]).join('\n'), /rm -rf/, 'a name-prefix sibling is not inside the clone');
});

test('cloneCleanupLines: a symlinked clone path, a path through a symlinked parent and a `..` spelling all match the real live path', () => {
  const clone = fakeClone();
  const holder = tmp('sterling-cut-links-');
  const link = join(holder, 'clone-link');
  symlinkSync(clone, link, 'dir');
  const parentLink = join(holder, 'parent-link');
  symlinkSync(dirname(clone), parentLink, 'dir');
  const dotdot = join(clone, 'projects', '..');
  mkdirSync(join(clone, 'projects'));
  const spellings = [link, join(parentLink, clone.split('/').pop()), dotdot];
  for (const spelling of spellings) {
    const asClone = cloneCleanupLines([spelling], [clone]).join('\n');
    assert.match(asClone, /live Sterling project/, `clone spelled ${spelling}`);
    assert.doesNotMatch(asClone, /rm -rf/, `clone spelled ${spelling}`);
    const asLive = cloneCleanupLines([clone], [spelling]).join('\n');
    assert.doesNotMatch(asLive, /rm -rf/, `live spelled ${spelling}`);
  }
});

test('cloneCleanupLines: a clone directory holding its own .sterling/sterling.db is a live project even when no registry lists it', () => {
  const clone = fakeClone();
  mkdirSync(join(clone, '.sterling'));
  writeFileSync(join(clone, '.sterling', 'sterling.db'), 'not a database: existence is the only thing checked');
  const lines = cloneCleanupLines([clone], []).join('\n');
  assert.match(lines, /holds its own project store \(\.sterling\/sterling\.db\).*keep it/);
  assert.doesNotMatch(lines, /rm -rf|delete it by hand/);
});

// ---- end to end: init.mjs from an installed copy, and from the authoring clone ----
//
// The plugin root is THIS checkout. It counts as an installed copy when it resolves
// under <CLAUDE_CONFIG_DIR>/plugins/cache (isInstalledCopy's second signal), so a
// config dir whose plugins/cache symlinks to this checkout's parent makes the real
// init run the installed branch with no copy of the tree.
function installedConfigDir(settings, known = {}) {
  const cfg = configDir(settings, known);
  symlinkSync(dirname(realpathSync(REPO)), join(cfg, 'plugins', 'cache'));
  return cfg;
}

function runInit(target, claudeConfigDir) {
  const r = spawnSync(process.execPath, [join(REPO, 'scripts', 'init.mjs'), '--target', target,
    '--project-name', 'cut-target', '--stack-tags', 'node', '--domain-description', 'node=test domain node', '--toolchain', 'node:**/*.mjs', '--backup-path', 'backups'], {
    encoding: 'utf8',
    cwd: target,
    timeout: 180_000,
    env: {
      ...process.env,
      HOME: tmp('sterling-cut-home-'), // init creates the declared domain stores under HOME
      STERLING_REGISTRY_DB: join(target, 'registry.db'),
      STERLING_PLUGIN_ROOT_MATCH: tmp('sterling-cut-prm-'),
      STERLING_CODEX_PROBE: 'absent',
      STERLING_CLAUDE_PROBE: 'ok',
      CLAUDE_CONFIG_DIR: claudeConfigDir,
    },
  });
  return { code: r.status, out: (r.stdout ?? '') + (r.stderr ?? '') };
}
const row = (out, item) => out.split('\n').find((l) => l.startsWith(item + ' ')) ?? '';

test('init from an installed copy: replaces the clone launcher, deletes the clone updater, switches on auto-update, names the clone for manual deletion', () => {
  const clone = fakeClone();
  const target = tmp('sterling-cut-project-');
  writeFileSync(join(target, 'sterling-launch.sh'), oldLauncher(clone));
  writeFileSync(join(target, UPDATE_LAUNCHER_NAME), oldUpdateBat(clone));
  const cfg = installedConfigDir({ extraKnownMarketplaces: { sterling: { source: SRC } } });

  const { code, out } = runInit(target, cfg);
  assert.equal(code, 0, out);

  const launcher = readFileSync(join(target, 'sterling-launch.sh'), 'utf8');
  assert.doesNotMatch(launcher, /--plugin-dir/, 'the launcher no longer overrides the installed plugin');
  assert.match(launcher, /newestInstalledSterling\(\)/, 'it is the installed shape');
  assert.match(row(out, 'sterling-launch.sh'), /replaced/);
  assert.ok(row(out, 'sterling-launch.sh').includes(clone), 'the replaced row names the old clone');

  assert.ok(!existsSync(join(target, UPDATE_LAUNCHER_NAME)), 'the clone updater is deleted');
  assert.match(row(out, UPDATE_LAUNCHER_NAME), /removed/);

  assert.equal(readSettings(cfg).extraKnownMarketplaces.sterling.autoUpdate, true, 'init switched auto-update on in the user settings');
  assert.deepEqual(readSettings(cfg).extraKnownMarketplaces.sterling.source, SRC, 'the entry\'s source is untouched');
  assert.ok(out.includes(fwd(join(cfg, 'settings.json'))) && out.includes('extraKnownMarketplaces.sterling.autoUpdate'), `one line names the file and key: ${out}`);
  assert.doesNotMatch(out, /plugin auto-update: .*not set/, 'no old warning');

  const tail = out.slice(out.lastIndexOf('old Sterling clone'));
  assert.ok(tail.includes(clone), `the end of the run names the clone to delete: ${out}`);
  assert.ok(existsSync(join(clone, '.git')), 'the clone itself is never deleted');
});

test('init from an installed copy: when the target IS the old clone, the end of the run says to keep it and never prints rm -rf', () => {
  const target = fakeClone();
  writeFileSync(join(target, 'sterling-launch.sh'), oldLauncher(target));
  const cfg = installedConfigDir({ extraKnownMarketplaces: { sterling: { autoUpdate: true } } });

  const { code, out } = runInit(target, cfg);
  assert.equal(code, 0, out);
  assert.match(row(out, 'sterling-launch.sh'), /replaced/);
  const tail = out.slice(out.lastIndexOf('old Sterling clone'));
  assert.ok(tail.includes(target.replace(/\\/g, '/')), `the end of the run names the directory: ${out}`);
  assert.match(tail, /live Sterling project on this machine/);
  assert.doesNotMatch(out, /rm -rf|delete it by hand/);
  assert.ok(existsSync(join(target, '.git')), 'the directory is untouched');
});

test('init from an installed copy: a differing launcher without --plugin-dir is left alone; auto-update on prints no warning and no clone step', () => {
  const target = tmp('sterling-cut-project-');
  const own = '#!/usr/bin/env bash\n# my own launcher\nexec claude\n';
  writeFileSync(join(target, 'sterling-launch.sh'), own);
  const cfg = installedConfigDir({ extraKnownMarketplaces: { sterling: { autoUpdate: true } } });

  const { code, out } = runInit(target, cfg);
  assert.equal(code, 0, out);
  assert.equal(readFileSync(join(target, 'sterling-launch.sh'), 'utf8'), own);
  assert.match(row(out, 'sterling-launch.sh'), /differs/);
  assert.doesNotMatch(out, /autoUpdate/);
  assert.doesNotMatch(out, /old Sterling clone/);
});

test('init from an installed copy: a launcher passing --plugin-dir for the user\'s own plugin is left byte-identical as differs, with no clone step', () => {
  const target = tmp('sterling-cut-project-');
  const own = '#!/usr/bin/env bash\n# my launcher, with my own plugin\nexec claude --plugin-dir ~/my-plugin\n';
  writeFileSync(join(target, 'sterling-launch.sh'), own);
  const cfg = installedConfigDir({ extraKnownMarketplaces: { sterling: { autoUpdate: true } } });

  const { code, out } = runInit(target, cfg);
  assert.equal(code, 0, out);
  assert.equal(readFileSync(join(target, 'sterling-launch.sh'), 'utf8'), own);
  assert.match(row(out, 'sterling-launch.sh'), /differs/);
  assert.doesNotMatch(out, /old Sterling clone/);
});

test('init from the authoring clone: a clone launcher and a clone updater are not touched by the cutover, and nothing about auto-update is said', () => {
  const clone = fakeClone();
  const target = tmp('sterling-cut-project-');
  const launcherBody = oldLauncher(clone);
  writeFileSync(join(target, 'sterling-launch.sh'), launcherBody);
  writeFileSync(join(target, UPDATE_LAUNCHER_NAME), oldUpdateBat(clone));

  const cfg = configDir({ extraKnownMarketplaces: { sterling: { source: SRC } } }, { sterling: { source: SRC } });
  const settingsBefore = readFileSync(join(cfg, 'settings.json'), 'utf8');
  const { code, out } = runInit(target, cfg);
  assert.equal(code, 0, out);
  assert.equal(readFileSync(join(cfg, 'settings.json'), 'utf8'), settingsBefore, 'the user settings are not touched on an authoring clone');
  assert.equal(readFileSync(join(target, 'sterling-launch.sh'), 'utf8'), launcherBody, 'a clone keeps today\'s leave-alone behaviour');
  assert.match(row(out, 'sterling-launch.sh'), /differs/);
  assert.ok(existsSync(join(target, UPDATE_LAUNCHER_NAME)), 'the updater is never deleted on a clone');
  assert.doesNotMatch(out, /autoUpdate/);
  assert.doesNotMatch(out, /old Sterling clone/);
});

test('init from an installed copy: the known_marketplaces.json source seeds the settings entry (2b), and a malformed settings.json is left untouched with a loud line', () => {
  const target = tmp('sterling-cut-project-');
  const cfg = installedConfigDir({ model: 'opus' });
  writeFileSync(join(cfg, 'plugins', 'known_marketplaces.json'), JSON.stringify({ sterling: { source: SRC, installLocation: '/x' } }));
  const first = runInit(target, cfg);
  assert.equal(first.code, 0, first.out);
  assert.deepEqual(readSettings(cfg), { model: 'opus', extraKnownMarketplaces: { sterling: { source: SRC, autoUpdate: true } } });

  const target2 = tmp('sterling-cut-project-');
  const bad = installedConfigDir('{ not json');
  const second = runInit(target2, bad);
  assert.equal(second.code, 0, second.out);
  assert.equal(readFileSync(join(bad, 'settings.json'), 'utf8'), '{ not json');
  assert.ok(second.out.includes(fwd(join(bad, 'settings.json'))) && /not valid JSON/.test(second.out), second.out);
});
