// architecture-projection tests (spec §15 via §12): architecture.md is a
// generated read-only projection over the extensible-set registries and their
// owning articles — never hand-maintained, degrades loud on article gaps.
import { test, before } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const NOW = '2026-06-10T12:00:00.000Z';

let SterlingStore;
before(async () => {
  ({ SterlingStore } = await import(pathToFileURL(join(root, 'packages', 'store', 'dist', 'index.js')).href));
});

function runScript(args, cwd) {
  const r = spawnSync(process.execPath, [join(root, 'scripts', 'architecture-projection.mjs'), ...args], {
    encoding: 'utf8',
    cwd,
    timeout: 60_000,
  });
  return { code: r.status, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

function articleRec(slug, intendedBehavior) {
  return {
    id: randomUUID(), type: 'feature_article', created_at: NOW, updated_at: NOW, author: 'conductor',
    status: 'active', superseded_by: null, links: [], scope: 'project', stack_tags: [],
    slug, title: `${slug} title`, what_it_does: 'body', intended_behavior: intendedBehavior,
    files: [{ path: 'src/x.mjs', role: 'impl' }],
    current_ac: [{ ac_id: 'AC1', text: 'x', verifiable_at: 'final' }],
    dependencies: { relies_on: [], relied_by: [] }, state: 'active', version: 1,
    history: [{ date: NOW, event: 'seed' }], live_test_refs: [],
  };
}

// The §15 set list is CLOSED here on purpose: a new extensible set must extend
// the projection too, and this totality pin is the check that catches a miss.
const SETS = ['signals', 'record-types', 'agents', 'hooks', 'tools', 'toolchain-adapters'];

test('§15 projection: every extensible set sectioned; owning articles quoted; gaps loud; marked generated', () => {
  const dir = mkdtempSync(join(tmpdir(), 'sterling-proj-'));
  mkdirSync(join(dir, '.sterling'), { recursive: true });
  writeFileSync(join(dir, '.sterling', 'config.json'), '{}');
  const store = new SterlingStore(join(dir, '.sterling', 'sterling.db'));
  try {
    store.create(articleRec('brain-signal-protocol', 'EXTEND-SIGNALS-GUIDANCE'));
    store.create(articleRec('record-schemas-registry', 'EXTEND-RECORDS-GUIDANCE'));
    store.close();

    const r = runScript([], dir);
    assert.equal(r.code, 0, `projection exits 0: ${r.stderr}`);

    const out = join(dir, 'architecture.md');
    assert.ok(existsSync(out), 'architecture.md written at the project root');
    const md = readFileSync(out, 'utf8');

    assert.match(md, /GENERATED by scripts\/architecture-projection\.mjs/, 'marked generated');
    assert.match(md, /DO NOT EDIT/, 'marked read-only');

    for (const set of SETS) {
      assert.match(md, new RegExp(`^## .*${set}`, 'mi'), `section for extensible set '${set}'`);
    }
    assert.match(md, /Registry:/, 'registry location named per set');
    assert.match(md, /Checks:/, 'guarding checks named per set');

    // seeded articles feed "Extending this" verbatim from intended_behavior
    assert.match(md, /EXTEND-SIGNALS-GUIDANCE/, 'signals article quoted');
    assert.match(md, /EXTEND-RECORDS-GUIDANCE/, 'record-types article quoted');

    // sets with no owning article degrade LOUD in-place, never omitted (P5)
    assert.match(md, /ARTICLE GAP/, 'missing owning articles surface as loud gaps');
    const gapCount = (md.match(/ARTICLE GAP/g) ?? []).length;
    assert.equal(gapCount, 4, 'exactly the four unseeded sets are gap-flagged');

    // regeneration is deterministic for an unchanged store (no wall-clock stamps)
    const r2 = runScript([], dir);
    assert.equal(r2.code, 0);
    assert.equal(readFileSync(out, 'utf8'), md, 'same store state regenerates byte-identical output');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('§15 projection: refuses outside an initialized project', () => {
  const bare = mkdtempSync(join(tmpdir(), 'sterling-proj-bare-'));
  try {
    const r = runScript([], bare);
    assert.notEqual(r.code, 0, 'no store → loud failure');
    assert.match(r.stderr, /not an initialized project/);
  } finally {
    rmSync(bare, { recursive: true, force: true });
  }
});

test('§15 projection freshness check (audit finding 25/43): passes when current, FAILS loud when the file lags the store', () => {
  const runFresh = (dir) => {
    const r = spawnSync(process.execPath, [join(root, 'scripts', 'check-projection-fresh.mjs'), dir], { encoding: 'utf8', cwd: dir, timeout: 60_000 });
    return { code: r.status, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
  };
  const dir = mkdtempSync(join(tmpdir(), 'sterling-proj-fresh-'));
  mkdirSync(join(dir, '.sterling'), { recursive: true });
  writeFileSync(join(dir, '.sterling', 'config.json'), '{}');
  const store = new SterlingStore(join(dir, '.sterling', 'sterling.db'));
  try {
    store.create(articleRec('brain-signal-protocol', 'g'));
    store.close();
    // generate the projection → freshness check passes
    assert.equal(runScript([], dir).code, 0);
    const pass = runFresh(dir);
    assert.equal(pass.code, 0, `fresh projection passes: ${pass.stderr}`);
    assert.match(pass.stdout, /projection freshness: ok/);

    // a NEWER article than the file's header → the check fails loud, names the fix
    const s2 = new SterlingStore(join(dir, '.sterling', 'sterling.db'));
    s2.create(articleRec('record-schemas-registry', 'g2')); // NOW+? — created_at NOW, but a fresh updated_at
    s2.close();
    // bump one article's updated_at past the file stamp via supersede
    const s3 = new SterlingStore(join(dir, '.sterling', 'sterling.db'));
    const arts = s3.query({ types: ['feature_article'], cap: 10 });
    s3.supersede(arts[0].id, { ...articleRec(arts[0].slug, 'g3'), version: 2, updated_at: '2099-01-01T00:00:00.000Z' });
    s3.close();
    const stale = runFresh(dir);
    assert.equal(stale.code, 1, 'a store newer than the committed projection fails the freshness check');
    assert.match(stale.stderr, /stale|Regenerate/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// Consumer-machine shape (decision e6240afe-e94b-4c1f-8eed-bafe32fb4d89): the
// clone HAS a store — init creates it — but no articles, because .sterling/ is
// gitignored and knowledge never travels with the repo. Comparing the committed
// projection against that store reported staleness that cannot exist there, and
// it aborted /sterling:update at its check step on every consumer machine.
test('an initialized store holding NO articles skips the freshness check loudly (consumer clone)', () => {
  const dir = mkdtempSync(join(tmpdir(), 'sterling-proj-consumer-'));
  mkdirSync(join(dir, '.sterling'), { recursive: true });
  writeFileSync(join(dir, '.sterling', 'config.json'), '{}');
  try {
    // store exists, holds nothing; a committed projection from the authoring machine
    new SterlingStore(join(dir, '.sterling', 'sterling.db')).close();
    writeFileSync(join(dir, 'architecture.md'), '# Architecture\n(store state as of 2026-07-26T20:01:51.260Z)\n');

    const r = spawnSync(process.execPath, [join(root, 'scripts', 'check-projection-fresh.mjs'), dir], {
      encoding: 'utf8', cwd: dir, timeout: 60_000,
    });
    assert.equal(r.status, 0, `an empty store must skip, not fail: ${r.stderr}`);
    assert.match(r.stdout, /skipped \(store holds no articles/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// The shape the empty-store skip above misses: a store with PLENTY of articles
// that still did not produce the committed projection. Unique among the battery,
// this arm's stated remedy would do harm on such a store — regenerating from a
// smaller store projects a smaller architecture.md, regressing a shared file.
test("store_authority 'secondary': a projection this store did not produce is reported, not failed, and never regenerated", () => {
  const dir = mkdtempSync(join(tmpdir(), 'sterling-proj-authority-'));
  mkdirSync(join(dir, '.sterling'), { recursive: true });
  const writeConfig = (authority) =>
    writeFileSync(join(dir, '.sterling', 'config.json'), JSON.stringify({ store_authority: authority }));
  try {
    const store = new SterlingStore(join(dir, '.sterling', 'sterling.db'));
    store.create(articleRec('brain-signal-protocol', 'g'));
    store.close();
    // a committed projection stamped from ANOTHER store — mismatched by construction
    const committed = '# Architecture\n(store state as of 2099-01-01T00:00:00.000Z)\n';
    writeFileSync(join(dir, 'architecture.md'), committed);

    const runFresh = () =>
      spawnSync(process.execPath, [join(root, 'scripts', 'check-projection-fresh.mjs'), dir], {
        encoding: 'utf8', cwd: dir, timeout: 60_000,
      });

    writeConfig('secondary');
    const secondary = runFresh();
    assert.equal(secondary.status, 0, `a secondary store must pass: ${secondary.stdout}${secondary.stderr}`);
    assert.match(secondary.stdout, /REPORTED, NOT FAILED/);
    assert.match(secondary.stdout, /do NOT regenerate here/, 'the harm must be named, not just the drift (P5)');
    assert.equal(readFileSync(join(dir, 'architecture.md'), 'utf8'), committed, 'the check never rewrites the projection');

    writeConfig('primary');
    const primary = runFresh();
    assert.equal(primary.status, 1, 'the producing store must still fail on a lagging projection');
    assert.match(primary.stderr, /stale|Regenerate/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
