// rulings-projection tests (decision 255f58b7, closes board 8f81704a):
// rulings.md is a generated read-only projection over the ruling corpus —
// ACTIVE decisions + anti_patterns, grouped by component — never
// hand-maintained. Mirrors scripts/tests/projection.test.mjs (architecture.md).
import { test, before } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const NOW = '2026-08-04T12:00:00.000Z';

let SterlingStore;
before(async () => {
  ({ SterlingStore } = await import(pathToFileURL(join(root, 'packages', 'store', 'dist', 'index.js')).href));
});

function runScript(args, cwd) {
  const r = spawnSync(process.execPath, [join(root, 'scripts', 'rulings-projection.mjs'), ...args], {
    encoding: 'utf8',
    cwd,
    timeout: 60_000,
  });
  return { code: r.status, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

function runFresh(dir) {
  const r = spawnSync(process.execPath, [join(root, 'scripts', 'check-projection-fresh.mjs'), dir], {
    encoding: 'utf8',
    cwd: dir,
    timeout: 60_000,
  });
  return { code: r.status, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

function envelope(type, extra = {}) {
  return {
    id: randomUUID(),
    type,
    created_at: NOW,
    updated_at: NOW,
    author: 'conductor',
    status: 'active',
    superseded_by: null,
    links: [],
    scope: 'project',
    stack_tags: [],
    ...extra,
  };
}

function decisionRecord(title, fileKeys = []) {
  return envelope('decision', {
    title,
    statement: `${title} — statement text.`,
    alternatives_rejected: [],
    rationale: 'rationale',
    file_keys: fileKeys,
  });
}

function antiPatternRecord(title, fileKeys = [], severity) {
  return envelope('anti_pattern', {
    title,
    trigger: 'trigger text',
    guidance: 'guidance',
    wrong_way: 'wrong way',
    right_way: 'right way',
    source_evidence: 'evidence',
    basis: 'codebase',
    file_keys: fileKeys,
    ...(severity ? { severity } : {}),
  });
}

function makeProject() {
  const dir = mkdtempSync(join(tmpdir(), 'sterling-rulings-'));
  mkdirSync(join(dir, '.sterling'), { recursive: true });
  writeFileSync(join(dir, '.sterling', 'config.json'), '{}');
  const store = new SterlingStore(join(dir, '.sterling', 'sterling.db'));
  return { dir, store, cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

test('rulings projection: groups by component (first file_key top-level segment), marks anti_pattern severity, marked generated', () => {
  const { dir, store, cleanup } = makeProject();
  try {
    store.create(decisionRecord('Schemas own path normalization', ['packages/schemas/src/records.ts']));
    store.create(antiPatternRecord('Never bypass the MCP surface', ['scripts/hooks/h15-store-guard.mjs'], 'block'));
    store.create(decisionRecord('No file_keys at all', []));

    const r = runScript([], dir);
    assert.equal(r.code, 0, `projection exits 0: ${r.stderr}`);

    const out = join(dir, 'rulings.md');
    assert.ok(existsSync(out), 'rulings.md written at the project root');
    const md = readFileSync(out, 'utf8');

    assert.match(md, /GENERATED by scripts\/rulings-projection\.mjs/, 'marked generated');
    assert.match(md, /DO NOT EDIT/, 'marked read-only');

    assert.match(md, /^## packages$/m, 'decision grouped under its file_key top-level segment');
    assert.match(md, /^## scripts$/m, 'anti_pattern grouped under its file_key top-level segment');
    assert.match(md, /^## \(uncomponented\)$/m, 'no file_keys -> uncomponented bucket');

    assert.match(md, /Schemas own path normalization/, 'decision title present');
    assert.match(md, /\[BLOCK\] Never bypass the MCP surface/, 'anti_pattern severity rendered');
    assert.match(md, /No file_keys at all/, 'uncomponented record present');

    // full ids present so a reader can knowledge_get straight from the line
    const decisions = store.query({ types: ['decision'], cap: 10 });
    for (const d of decisions) assert.match(md, new RegExp(d.id), `full id for '${d.title}' present`);

    // regeneration is deterministic for an unchanged store (no wall-clock stamps)
    const r2 = runScript([], dir);
    assert.equal(r2.code, 0);
    assert.equal(readFileSync(out, 'utf8'), md, 'same store state regenerates byte-identical output');
  } finally {
    cleanup();
  }
});

test('rulings projection: clips a long title but keeps the full id', () => {
  const { dir, store, cleanup } = makeProject();
  try {
    const longTitle = 'x'.repeat(200);
    const rec = decisionRecord(longTitle, ['packages/store/src/index.ts']);
    store.create(rec);
    const r = runScript([], dir);
    assert.equal(r.code, 0);
    const md = readFileSync(join(dir, 'rulings.md'), 'utf8');
    assert.match(md, /x{100}…/, 'title clipped');
    assert.doesNotMatch(md, new RegExp(`${longTitle}\\b`), 'the unclipped 200-char title does not appear whole');
  } finally {
    cleanup();
  }
});

test('rulings projection: superseded records are excluded — only ACTIVE rulings render', () => {
  const { dir, store, cleanup } = makeProject();
  try {
    const rec = decisionRecord('Original ruling', ['packages/x.ts']);
    const created = store.create(rec);
    store.supersede(created.id, { ...decisionRecord('Superseding ruling', ['packages/x.ts']), version: 2 });
    const r = runScript([], dir);
    assert.equal(r.code, 0);
    const md = readFileSync(join(dir, 'rulings.md'), 'utf8');
    assert.doesNotMatch(md, /Original ruling/, 'the superseded record is not projected');
    assert.match(md, /Superseding ruling/, 'the live record is');
  } finally {
    cleanup();
  }
});

test('rulings projection: refuses outside an initialized project', () => {
  const bare = mkdtempSync(join(tmpdir(), 'sterling-rulings-bare-'));
  try {
    const r = runScript([], bare);
    assert.notEqual(r.code, 0, 'no store → loud failure');
    assert.match(r.stderr, /not an initialized project/);
  } finally {
    rmSync(bare, { recursive: true, force: true });
  }
});

test('rulings projection: an empty corpus still writes a valid, marked file', () => {
  const { dir, cleanup } = makeProject();
  try {
    const r = runScript([], dir);
    assert.equal(r.code, 0);
    const md = readFileSync(join(dir, 'rulings.md'), 'utf8');
    assert.match(md, /GENERATED by scripts\/rulings-projection\.mjs/);
    assert.match(md, /no active decisions or anti_patterns/);
  } finally {
    cleanup();
  }
});

// --- freshness (shares check-projection-fresh.mjs with architecture.md) -----

test('rulings freshness: passes when current, FAILS loud when the file lags the store', () => {
  const { dir, store, cleanup } = makeProject();
  try {
    store.create(decisionRecord('Seed ruling', ['packages/x.ts']));
    store.close();
    assert.equal(runScript([], dir).code, 0);
    const pass = runFresh(dir);
    assert.equal(pass.code, 0, `fresh projection passes: ${pass.stderr}`);
    assert.match(pass.stdout, /projection freshness: ok \(rulings\.md/);

    // a NEWER decision than the file's header -> the check fails loud, names the fix
    const s2 = new SterlingStore(join(dir, '.sterling', 'sterling.db'));
    s2.create({ ...decisionRecord('Newer ruling', ['packages/y.ts']), updated_at: '2099-01-01T00:00:00.000Z' });
    s2.close();
    const stale = runFresh(dir);
    assert.equal(stale.code, 1, 'a store newer than the committed rulings.md fails the freshness check');
    assert.match(stale.stderr, /rulings\.md is stale/);
    assert.match(stale.stderr, /rulings-projection\.mjs/);
  } finally {
    cleanup();
  }
});

test('rulings freshness: an initialized store holding no decisions/anti_patterns skips loudly (consumer clone)', () => {
  const dir = mkdtempSync(join(tmpdir(), 'sterling-rulings-consumer-'));
  mkdirSync(join(dir, '.sterling'), { recursive: true });
  writeFileSync(join(dir, '.sterling', 'config.json'), '{}');
  try {
    new SterlingStore(join(dir, '.sterling', 'sterling.db')).close();
    writeFileSync(join(dir, 'rulings.md'), '# Rulings\n(store state as of 2026-08-01T00:00:00.000Z)\n');
    const r = runFresh(dir);
    assert.equal(r.code, 0, `an empty store must skip, not fail: ${r.stderr}`);
    assert.match(r.stdout, /skipped \(store holds no decisions or anti_patterns/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// The two projections are checked independently — a stale architecture.md must
// not mask, or be masked by, a fresh rulings.md (and vice versa).
test('freshness check evaluates architecture.md and rulings.md independently', () => {
  const { dir, store, cleanup } = makeProject();
  try {
    store.create(decisionRecord('Seed ruling', ['packages/x.ts']));
    store.close();
    // Only generate rulings.md — architecture.md is absent entirely.
    assert.equal(runScript([], dir).code, 0);
    const r = runFresh(dir);
    assert.equal(r.code, 0);
    assert.match(r.stdout, /skipped \(no architecture\.md\)/);
    assert.match(r.stdout, /projection freshness: ok \(rulings\.md/);
  } finally {
    cleanup();
  }
});
