// Consumer cutover [S6] (decision s6-consumer-cutover-init-on-installed-copy-fixes-
// launchers): what /sterling:init, run from an INSTALLED plugin copy, needs to move a
// consumer project off its old clone. init owns the writes; this module only reads and
// renders text:
//   - cloneLauncherTarget: is a sterling-launch.sh a clone launcher (one that starts
//     claude with --plugin-dir, which overrides the installed plugin — finding 9bce09a9)?
//   - marketplaceAutoUpdate / autoUpdateWarning: is "autoUpdate": true set on
//     extraKnownMarketplaces.sterling in the user-level settings.json? Never written.
//   - cloneCleanupLines: the manual step naming each old clone. Nothing deletes a clone.
// The sterling-update.bat recogniser lives beside its renderer in update-launcher.mjs.
//
// Builtins only, like the other scripts/lib launcher helpers.
import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const fwd = (p) => p.replace(/\\/g, '/');

/**
 * TWO conditions, both required:
 *   1. a `--plugin-dir` flag outside comments (full-line and trailing ` # ...` comments
 *      are stripped first): every authoring-shape render has
 *      `"$CLAUDE_BIN" --plugin-dir "$PLUGIN_DIR"`, and the installed shape has none
 *      (scripts/lib/launcher-tmux.mjs);
 *   2. it is Sterling's: the file carries the generated header comment
 *      (`GENERATED by /sterling:init`, templates/launcher-tmux.sh line 3), OR the
 *      extracted path is a Sterling clone on disk (.git plus a plugin.json named
 *      sterling). A launcher for the user's own plugin meets neither and is left alone.
 * The clone path is the generated `PLUGIN_DIR="<path>"` assignment, else a literal
 * `--plugin-dir <path>`; an unresolved variable leaves it null.
 * @returns {{clonePath: string|null, signal: 'generated-header'|'sterling-clone'} | null}
 *   null when the text is not a Sterling clone launcher
 */
export function cloneLauncherTarget(text) {
  const raw = text.replace(/\r\n/g, '\n').split('\n');
  const code = raw.map((l) => l.replace(/(^|\s)#.*$/, '').trimEnd());
  const flagLine = code.find((l) => /(^|\s)--plugin-dir(\s|=|$)/.test(l));
  if (!flagLine) return null;
  const assigned = code.map((l) => /^\s*PLUGIN_DIR="([^"$]+)"$/.exec(l)).find(Boolean);
  const literal = /--plugin-dir[ =](?:"([^"$]+)"|([^\s"'$][^\s"']*))/.exec(flagLine);
  const clonePath = assigned ? fwd(assigned[1]) : literal ? fwd(literal[1] ?? literal[2]) : null;
  if (raw.some((l) => /^\s*#.*GENERATED by \/sterling:init/.test(l))) return { clonePath, signal: 'generated-header' };
  if (clonePath && inspectClone(clonePath).kind === 'clone') return { clonePath, signal: 'sterling-clone' };
  return null;
}

/** <CLAUDE_CONFIG_DIR or <home>/.claude>/settings.json — the same root as pluginCacheDir. */
export function userSettingsPath({ env = process.env, home = homedir() } = {}) {
  return join(env.CLAUDE_CONFIG_DIR || join(home, '.claude'), 'settings.json');
}

/**
 * Reads the user-level settings.json and reports whether
 * extraKnownMarketplaces.sterling.autoUpdate is true. Only reads; a missing file is
 * `missing`, an unreadable or unparseable one is `unreadable` (never guessed at).
 * @returns {{path: string, enabled: boolean, entry?: object, missing?: true, unreadable?: string}}
 */
export function marketplaceAutoUpdate({ env = process.env, home = homedir(), readFile = readFileSync } = {}) {
  const path = userSettingsPath({ env, home });
  let raw;
  try {
    raw = readFile(path, 'utf8');
  } catch (err) {
    if (err?.code === 'ENOENT') return { path, enabled: false, missing: true };
    return { path, enabled: false, unreadable: err?.code ?? err?.message ?? String(err) };
  }
  let settings;
  try {
    settings = JSON.parse(raw);
  } catch (err) {
    return { path, enabled: false, unreadable: `not valid JSON (${err?.message ?? err})` };
  }
  const entry = settings?.extraKnownMarketplaces?.sterling;
  if (!entry || typeof entry !== 'object' || Array.isArray(entry)) return { path, enabled: false };
  return { path, enabled: entry.autoUpdate === true, entry };
}

// The /plugin -> Marketplaces toggle keeps its own setting in a file whose shape was
// never measured, so init does not read it; the warning says so instead of guessing.
const TOGGLE_NOTE = 'If you already switched auto-update on in /plugin -> Marketplaces, ignore this warning: init does not read that setting.';

/** The ONE loud line init prints when settings.json does not set auto-update, or null when it does. */
export function autoUpdateWarning(check) {
  if (check.enabled) return null;
  const where = fwd(check.path);
  const head = 'plugin auto-update: "autoUpdate": true is not set for the sterling marketplace in settings.json';
  if (check.missing) {
    return `${head} — ${where} does not exist. To set it, add "autoUpdate": true to extraKnownMarketplaces.sterling there. ${TOGGLE_NOTE}`;
  }
  if (check.unreadable) {
    return `${head} — ${where} could not be read: ${check.unreadable}. To set it, add "autoUpdate": true to extraKnownMarketplaces.sterling there. ${TOGGLE_NOTE}`;
  }
  if (!check.entry) {
    return `${head} — ${where} has no extraKnownMarketplaces.sterling entry. Add "autoUpdate": true to that entry. ${TOGGLE_NOTE}`;
  }
  const fixed = JSON.stringify({ sterling: { ...check.entry, autoUpdate: true } });
  return `${head} — extraKnownMarketplaces.sterling in ${where} has no "autoUpdate": true. To set it, replace that entry with: "extraKnownMarketplaces": ${fixed} (init never writes this file). ${TOGGLE_NOTE}`;
}

// A JSON file read for one field. Absent (ENOENT, or ENOTDIR on the way) and malformed
// JSON are 'absent'; any other read failure is returned as its error code, never thrown.
function readJsonField(path, field) {
  try {
    return { value: JSON.parse(readFileSync(path, 'utf8'))?.[field] };
  } catch (err) {
    if (err?.code === 'ENOENT' || err?.code === 'ENOTDIR' || err instanceof SyntaxError) return { absent: true };
    return { error: err?.code ?? err?.message ?? String(err) };
  }
}

/**
 * Is `dir` a Sterling clone (.git plus .claude-plugin/plugin.json named sterling), and
 * does its own .sterling/config.json declare machine_role authoring (H1's MACHINE ROLE)?
 * @returns {{kind: 'clone', authoring: boolean} | {kind: 'not-clone'} | {kind: 'error', code: string}}
 */
function inspectClone(dir) {
  if (!existsSync(join(dir, '.git'))) return { kind: 'not-clone' };
  const name = readJsonField(join(dir, '.claude-plugin', 'plugin.json'), 'name');
  if (name.error) return { kind: 'error', code: name.error };
  if (name.value !== 'sterling') return { kind: 'not-clone' };
  const role = readJsonField(join(dir, '.sterling', 'config.json'), 'machine_role');
  if (role.error) return { kind: 'error', code: role.error };
  return { kind: 'clone', authoring: role.value === 'authoring' };
}

const trimSlash = (p) => (p.length > 1 ? p.replace(/\/+$/, '') : p);

/** The manual clone-deletion step, one line per distinct named path; [] when none.
 *  Runs after every init write, so an inspection failure is printed, never thrown. */
export function cloneCleanupLines(paths) {
  const unique = [...new Set(paths.filter(Boolean).map((p) => trimSlash(fwd(p))))];
  if (unique.length === 0) return [];
  const lines = ['old Sterling clone — this project used to run Sterling from a clone. Init never deletes a clone:'];
  for (const p of unique) {
    const found = inspectClone(p);
    if (found.kind === 'error') {
      lines.push(`  ${p} — could not inspect ${p}: ${found.code}; check it by hand before deleting anything`);
    } else if (found.kind === 'not-clone') {
      lines.push(`  ${p} — not a Sterling clone on this machine (already removed or moved); nothing to delete`);
    } else if (found.authoring) {
      lines.push(`  ${p} — this machine's authoring clone (machine_role authoring in its .sterling/config.json); keep it`);
    } else {
      lines.push(`  ${p} — delete it by hand once no project on this machine launches from it (rm -rf "${p}")`);
    }
  }
  return lines;
}
