// Consumer cutover [S6] (decision s6-consumer-cutover-init-on-installed-copy-fixes-
// launchers): what /sterling:init, run from an INSTALLED plugin copy, needs to move a
// consumer project off its old clone. init owns the writes, except the one settings.json
// switch below; the rest only reads and renders text:
//   - cloneLauncherTarget: is a sterling-launch.sh a clone launcher (one that starts
//     claude with --plugin-dir, which overrides the installed plugin — finding 9bce09a9)?
//   - enableMarketplaceAutoUpdate: switches on "autoUpdate": true for the sterling marketplace
//     in the user-level settings.json (user-ruled 2026-10-06 through the question form, "Init
//     switches it on", over the warn-only rule of the decision above). The one user-level file
//     init writes; deleting a clone stays manual.
//   - cloneCleanupLines: the manual step naming each old clone. Nothing deletes a clone,
//     and a clone that is the init target or a registered project is never offered for it.
// The sterling-update.bat recogniser lives beside its renderer in update-launcher.mjs.
//
// Builtins plus the shared path comparison (@sterling/schemas), which init and update bundle.
import { chmodSync, existsSync, readFileSync, realpathSync, renameSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { sameLocationAnyHost, isUnderLocationAnyHost } from '@sterling/schemas';

const fwd = (p) => p.replace(/\\/g, '/');

/**
 * TWO conditions, both required:
 *   1. a `--plugin-dir` flag outside comments (full-line and trailing ` # ...` comments
 *      are stripped first): every authoring-shape render has
 *      `"$CLAUDE_BIN" --plugin-dir "$PLUGIN_DIR"`, and the installed shape has none
 *      (scripts/lib/launcher-tmux.mjs);
 *   2. it is Sterling's: the file carries the generated header comment
 *      (`GENERATED by /sterling:init`, templates/launcher-tmux.sh line 3), OR the
 *      extracted path is a Sterling clone on disk (.git plus a plugin.json named
 *      sterling). A launcher for the user's own plugin meets neither and is left alone.
 * The clone path is the generated `PLUGIN_DIR="<path>"` assignment, else a literal
 * `--plugin-dir <path>`; an unresolved variable leaves it null.
 * @returns {{clonePath: string|null, signal: 'generated-header'|'sterling-clone'} | null}
 *   null when the text is not a Sterling clone launcher
 */
export function cloneLauncherTarget(text) {
  const raw = text.replace(/\r\n/g, '\n').split('\n');
  const code = raw.map((l) => l.replace(/(^|\s)#.*$/, '').trimEnd());
  const flagLine = code.find((l) => /(^|\s)--plugin-dir(\s|=|$)/.test(l));
  if (!flagLine) return null;
  const assigned = code.map((l) => /^\s*PLUGIN_DIR="([^"$]+)"$/.exec(l)).find(Boolean);
  const literal = /--plugin-dir[ =](?:"([^"$]+)"|([^\s"'$][^\s"']*))/.exec(flagLine);
  const clonePath = assigned ? fwd(assigned[1]) : literal ? fwd(literal[1] ?? literal[2]) : null;
  if (raw.some((l) => /^\s*#.*GENERATED by \/sterling:init/.test(l))) return { clonePath, signal: 'generated-header' };
  if (clonePath && inspectClone(clonePath).kind === 'clone') return { clonePath, signal: 'sterling-clone' };
  return null;
}

/** <CLAUDE_CONFIG_DIR or <home>/.claude>/settings.json — the same config dir that holds Claude Code's plugin cache (installRoots in sterling-roots.mjs). */
export function userSettingsPath({ env = process.env, home = homedir() } = {}) {
  return join(env.CLAUDE_CONFIG_DIR || join(home, '.claude'), 'settings.json');
}

// Claude Code's plugins root: CLAUDE_CODE_PLUGIN_CACHE_DIR when set, else <config dir>/plugins
// (https://code.claude.com/docs/en/plugins/loading, "Find plugins on disk").
function knownMarketplacesPath({ env, home }) {
  return join(env.CLAUDE_CODE_PLUGIN_CACHE_DIR || join(env.CLAUDE_CONFIG_DIR || join(home, '.claude'), 'plugins'), 'known_marketplaces.json');
}

const isObject = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);

// One JSON object read from disk. Failures carry only a fixed phrase or the error code,
// never err.message: a JSON.parse message can span lines and quote the file (anti-pattern
// putting-a-json-parse-or-file-read-error-message-into-one-lin). Line endings and the
// trailing newline are returned so a rewrite can keep them; a leading BOM is dropped and
// a rewrite does not put it back.
function readJsonObject(path, readFile) {
  let raw;
  try {
    raw = readFile(path, 'utf8');
  } catch (err) {
    if (err?.code === 'ENOENT') return { missing: true };
    return { unreadable: err?.code ?? 'unknown error' };
  }
  const text = raw.charCodeAt(0) === 0xfeff ? raw.slice(1) : raw;
  let value;
  try {
    value = JSON.parse(text);
  } catch {
    return { invalid: 'not valid JSON' };
  }
  if (!isObject(value)) return { invalid: 'not a JSON object' };
  return { value, eol: text.includes('\r\n') ? '\r\n' : '\n', trailingNewline: /\r?\n$/.test(text) };
}

const MANUAL = 'To switch it on by hand: /plugin, Marketplaces, sterling, Enable auto-update.';

/**
 * Switches on auto-update for the sterling marketplace in the user-level settings.json.
 * Claude Code takes the first of these that is set: autoUpdate on the settings file's
 * extraKnownMarketplaces entry, then on the known_marketplaces.json entry (the /plugin toggle
 * writes it), then the default, off for sterling (code.claude.com/docs/en/plugins/loading,
 * "Which marketplaces and plugins auto-update").
 *   - already true by that rule: no write, line null.
 *   - settings entry exists, autoUpdate unset: autoUpdate: true is set on it; its source and
 *     every other key stay as they were.
 *   - no settings entry but known_marketplaces.json has sterling with a source object: the entry
 *     is created with exactly that source plus autoUpdate: true. known_marketplaces.json is
 *     Claude Code's own state file and is never written; no source is ever invented.
 *   - an explicit autoUpdate: false (settings entry, or the known entry when settings is silent)
 *     is a deliberate choice: not flipped, a line says how to turn it on.
 *   - settings.json or known_marketplaces.json missing, unreadable or malformed: nothing is
 *     written and the line names the file and the manual step.
 * A write goes to the file the path really names, through a temp file beside it that carries
 * the original's mode, so a symlinked settings.json stays a link and a 0600 file stays 0600.
 * A path whose real file cannot be resolved is not written.
 * The call site runs this on an installed copy only; an authoring clone never reaches it.
 * @returns {{status: string, path: string, line: string|null}} status is one of already-on,
 *   written, explicit-off, no-entry, no-source, settings-missing, settings-unreadable,
 *   settings-unwritable, settings-invalid, known-missing, known-unreadable, known-invalid
 */
export function enableMarketplaceAutoUpdate({ env = process.env, home = homedir(), readFile = readFileSync, writeFile = writeFileSync, rename = renameSync } = {}) {
  const path = userSettingsPath({ env, home });
  const knownPath = knownMarketplacesPath({ env, home });
  const where = fwd(path);
  const knownWhere = fwd(knownPath);
  const out = (status, line) => ({ status, path, line });
  const stop = (status, file, why) => out(status, `plugin auto-update: not switched on, ${fwd(file)} ${why}. ${MANUAL}`);

  const settings = readJsonObject(path, readFile);
  if (settings.missing) return stop('settings-missing', path, 'does not exist, so init left it alone');
  if (settings.unreadable) return stop('settings-unreadable', path, `could not be read (${settings.unreadable}), so init left it alone`);
  if (settings.invalid) return stop('settings-invalid', path, `is ${settings.invalid}, so init left it alone`);

  const markets = settings.value.extraKnownMarketplaces;
  if (markets !== undefined && !isObject(markets)) return stop('settings-invalid', path, 'has an extraKnownMarketplaces that is not a JSON object, so init left it alone');
  const entry = markets?.sterling;
  if (entry !== undefined && !isObject(entry)) return stop('settings-invalid', path, 'has an extraKnownMarketplaces.sterling that is not a JSON object, so init left it alone');
  if (entry?.autoUpdate === true) return out('already-on', null);
  if (entry?.autoUpdate === false) {
    return out('explicit-off', `plugin auto-update: off by an explicit setting, "autoUpdate": false on extraKnownMarketplaces.sterling in ${where}. Init does not override it; set "autoUpdate": true there, or use /plugin, Marketplaces, sterling, Enable auto-update.`);
  }

  const known = readJsonObject(knownPath, readFile);
  if (known.missing) return stop('known-missing', knownPath, 'does not exist, so init cannot tell whether the /plugin toggle is on');
  if (known.unreadable) return stop('known-unreadable', knownPath, `could not be read (${known.unreadable}), so init cannot tell whether the /plugin toggle is on`);
  if (known.invalid) return stop('known-invalid', knownPath, `is ${known.invalid}, so init cannot tell whether the /plugin toggle is on`);
  const knownEntry = known.value.sterling;
  if (isObject(knownEntry) && knownEntry.autoUpdate === true) return out('already-on', null);
  if (isObject(knownEntry) && knownEntry.autoUpdate === false) {
    return out('explicit-off', `plugin auto-update: off by an explicit setting, "autoUpdate": false on the sterling entry in ${knownWhere} (the /plugin toggle). Init does not override it; use /plugin, Marketplaces, sterling, Enable auto-update.`);
  }

  let next;
  if (entry) {
    next = { ...markets, sterling: { ...entry, autoUpdate: true } };
  } else if (isObject(knownEntry) && isObject(knownEntry.source)) {
    next = { ...markets, sterling: { source: knownEntry.source, autoUpdate: true } };
  } else if (isObject(knownEntry)) {
    return stop('no-source', knownPath, 'has a sterling entry with no source object to copy into settings.json, so init wrote nothing');
  } else {
    return out('no-entry', `plugin auto-update: not switched on, no sterling marketplace entry in ${where} or ${knownWhere}. ${MANUAL}`);
  }

  const { eol, trailingNewline } = settings;
  let body = JSON.stringify({ ...settings.value, extraKnownMarketplaces: next }, null, 2);
  if (eol === '\r\n') body = body.replace(/\n/g, '\r\n');
  if (trailingNewline) body += eol;
  let target;
  let mode;
  try {
    target = realpathSync(path);
    mode = statSync(target).mode & 0o7777;
  } catch (err) {
    return stop('settings-unwritable', path, `could not be resolved to the file it names (${err?.code ?? 'unknown error'}), so init left it alone`);
  }
  const tmp = `${target}.tmp-${randomUUID()}`;
  try {
    writeFile(tmp, body, { mode });
    chmodSync(tmp, mode); // the mode given at creation is cut by the umask
    rename(tmp, target);
  } catch (err) {
    try { unlinkSync(tmp); } catch { /* the temp file may never have been created */ }
    return stop('settings-unwritable', path, `could not be written (${err?.code ?? 'unknown error'}), so init left it alone`);
  }
  return out('written', `plugin auto-update: switched on. Init set extraKnownMarketplaces.sterling.autoUpdate to true in ${where}; it takes effect from the next session.`);
}

// A JSON file read for one field. Absent (ENOENT, or ENOTDIR on the way) and malformed
// JSON are 'absent'; any other read failure is returned as its error code, never thrown.
function readJsonField(path, field) {
  try {
    return { value: JSON.parse(readFileSync(path, 'utf8'))?.[field] };
  } catch (err) {
    if (err?.code === 'ENOENT' || err?.code === 'ENOTDIR' || err instanceof SyntaxError) return { absent: true };
    return { error: err?.code ?? err?.message ?? String(err) };
  }
}

/**
 * Is `dir` a Sterling clone (.git plus .claude-plugin/plugin.json named sterling), and
 * does its own .sterling/config.json declare machine_role authoring (H1's MACHINE ROLE)?
 * @returns {{kind: 'clone', authoring: boolean} | {kind: 'not-clone'} | {kind: 'error', code: string}}
 */
function inspectClone(dir) {
  if (!existsSync(join(dir, '.git'))) return { kind: 'not-clone' };
  const name = readJsonField(join(dir, '.claude-plugin', 'plugin.json'), 'name');
  if (name.error) return { kind: 'error', code: name.error };
  if (name.value !== 'sterling') return { kind: 'not-clone' };
  const role = readJsonField(join(dir, '.sterling', 'config.json'), 'machine_role');
  if (role.error) return { kind: 'error', code: role.error };
  return { kind: 'clone', authoring: role.value === 'authoring' };
}

const trimSlash = (p) => (p.length > 1 ? p.replace(/\/+$/, '') : p);

// The location a path really names: symlinks and '..' resolved when it exists, else the
// string as given (the same helper shape as scripts/domains.mjs). A string comparison alone
// would miss a clone reached through a symlink or a '..' spelling.
const real = (p) => {
  try {
    return existsSync(p) ? realpathSync(p) : p;
  } catch {
    return p; // unresolvable (permissions, a loop): compare the string; inspectClone then reports what it can read
  }
};

/** The manual clone-deletion step, one line per distinct named path; [] when none.
 *  Runs after every init write, so an inspection failure is printed, never thrown.
 *  `liveProjectPaths` are the init target plus every registered project. A clone path that is
 *  one of them, or CONTAINS one, holds a live project's store and history, so it gets a keep
 *  line and never a deletion command (a clone INSIDE a live project keeps the hint); so does
 *  a clone holding its own .sterling/sterling.db (checked by existence only). Pass [] only
 *  when there are known to be none. null or omitted means the registry could not be read:
 *  every path is then treated as live (fail closed). */
export function cloneCleanupLines(paths, liveProjectPaths) {
  const unique = [...new Set(paths.filter(Boolean).map((p) => trimSlash(fwd(p))))];
  if (unique.length === 0) return [];
  const lines = ['old Sterling clone — this project used to run Sterling from a clone. Init never deletes a clone:'];
  for (const p of unique) {
    if (liveProjectPaths === null || liveProjectPaths === undefined) {
      lines.push(`  ${p} — the project registry could not be read, so this is treated as a live project and not offered for deletion; keep it unless you have checked by hand that no project on this machine uses it`);
      continue;
    }
    const here = real(p);
    const live = liveProjectPaths.map(real);
    if (live.some((l) => sameLocationAnyHost(here, l))) {
      lines.push(`  ${p} — a live Sterling project on this machine with its own store; keep it. Only the --plugin-dir launch was replaced; this directory is not an old clone to delete`);
      continue;
    }
    if (live.some((l) => isUnderLocationAnyHost(l, here))) {
      lines.push(`  ${p} — contains a live Sterling project on this machine; keep it. Deleting this directory would delete that project with it`);
      continue;
    }
    const found = inspectClone(p);
    if (found.kind === 'error') {
      lines.push(`  ${p} — could not inspect ${p}: ${found.code}; check it by hand before deleting anything`);
    } else if (found.kind === 'not-clone') {
      lines.push(`  ${p} — not a Sterling clone on this machine (already removed or moved); nothing to delete`);
    } else if (found.authoring) {
      lines.push(`  ${p} — this machine's authoring clone (machine_role authoring in its .sterling/config.json); keep it`);
    } else if (existsSync(join(p, '.sterling', 'sterling.db'))) {
      lines.push(`  ${p} — holds its own project store (.sterling/sterling.db), so it is a live Sterling project even if no registry lists it; keep it`);
    } else {
      lines.push(`  ${p} — delete it by hand once no project on this machine launches from it (rm -rf "${p}")`);
    }
  }
  return lines;
}
