#!/usr/bin/env bash
# Sterling launch engine (spec section 11) - the WSL/Linux tmux session: a left
# pane running Claude Code or OpenCode and a right pane running the TUI.
# GENERATED by /sterling:init from templates/launcher-tmux.sh. Machine-specific;
# gitignored; regenerable by re-running /sterling:init. The openers
# (claude-code.bat / opencode.bat on Windows, claude-code.sh / opencode.sh on
# Linux) all call this script.
#
# Usage:
#   sterling-launch.sh [claude]   Claude Code + TUI session (re-attach if running)
#   sterling-launch.sh opencode   OpenCode + TUI session (re-attach if running)
#   sterling-launch.sh tui        add the TUI pane to the caller's session
set -euo pipefail

MODE="${1:-claude}"
SESSION="{{SESSION}}"   # per checkout (basename + path hash); each mode adds -claude or -opencode
LEGACY_SESSION="{{LEGACY_SESSION}}"   # the name launchers used before the hash and the mode suffix

# --- generated paths (machine-detected by init) ---
{{PLUGIN_PATHS}}
SPLIT_RATIO={{SPLIT_RATIO}}   # right-pane width, percent

# node/claude/opencode resolved at runtime (PATH first, then the usual install dirs)
CLAUDE_BIN="${CLAUDE_BIN:-$(command -v claude || true)}"
OPENCODE_BIN="${OPENCODE_BIN:-$(command -v opencode || true)}"
[ -n "$OPENCODE_BIN" ] || { [ ! -x "$HOME/.opencode/bin/opencode" ] || OPENCODE_BIN="$HOME/.opencode/bin/opencode"; }
NODE_BIN="${NODE_BIN:-$(command -v node || true)}"
[ -n "$NODE_BIN" ] || NODE_BIN="$(ls -d "$HOME"/.local/node-v*-linux-x64/bin/node 2>/dev/null | head -1)"

WORKDIR="$PWD"
STORE="$WORKDIR/.sterling/sterling.db"
TUI_LOCK="$WORKDIR/.sterling/transient/tui.lock"

# --- fail loud on missing inputs (P5) ---
[ -n "$NODE_BIN" ] || { echo "sterling-launch: 'node' not found on PATH (set NODE_BIN)" >&2; exit 1; }
command -v tmux >/dev/null || { echo "sterling-launch: 'tmux' not installed" >&2; exit 1; }
[ -n "$TUI_BUNDLE" ] && [ -f "$TUI_BUNDLE" ] || { echo "sterling-launch: TUI bundle missing: ${TUI_BUNDLE:-no installed Sterling found}" >&2; exit 1; }
[ -f "$STORE" ]      || { echo "sterling-launch: store missing: $STORE (run from a project root)" >&2; exit 1; }

# '=' asks tmux for an exact name: without it sterling-x would match sterling-x-claude.
# set-option and split-window take a pane target, so they need the trailing ':'.
running() { tmux has-session -t "=$1" 2>/dev/null; }

# The legacy name is basename-only, so another checkout with the same directory
# name can own it: it counts as this checkout's only when it started in WORKDIR.
legacy_running() {
  running "$LEGACY_SESSION" && [ "$(tmux display -p -t "=$LEGACY_SESSION:" '#{session_path}' 2>/dev/null || true)" = "$WORKDIR" ]
}

has_tui_pane() {
  local cmds
  cmds="$(tmux list-panes -s -t "=$1" -F '#{pane_start_command}' 2>/dev/null || true)"
  [[ "$cmds" == *sterling-tui.mjs* ]]
}

# The TUI runs once per store (packages/tui/src/lock.ts). Print "<pid> <ppid>" of
# the TUI holding tui.lock: the pid is alive, its /proc start time equals the one
# in the lock (a recycled pid has a later one), and its command line is the TUI.
tui_lock_owner() {
  local pid="" start="" stat cmd
  [ -f "$TUI_LOCK" ] || return 0
  read -r pid start _ < "$TUI_LOCK" || true
  [[ "$pid" =~ ^[1-9][0-9]*$ ]] || return 0
  stat="$(cat "/proc/$pid/stat" 2>/dev/null)" || return 0
  local fields=(${stat##*\)})   # after the last ')': state is [0], ppid [1], starttime [19]
  [ -z "$start" ] || [ "${fields[19]:-}" = "$start" ] || return 0
  cmd="$(tr '\0' ' ' < "/proc/$pid/cmdline" 2>/dev/null)" || return 0
  [[ "$cmd" == *sterling-tui* ]] || return 0
  echo "$pid ${fields[1]:-0}"
}

# The TUI follows the launcher opened last: stop the one another session holds.
take_tui() {
  local owner pid ppid from i
  owner="$(tui_lock_owner)"
  [ -n "$owner" ] || return 0
  read -r pid ppid <<< "$owner"
  from="$(tmux list-panes -a -F '#{pane_pid} #{session_name}' 2>/dev/null \
    | awk -v a="$pid" -v b="$ppid" '$1 == a || $1 == b { print $2; exit }' || true)"
  if ! kill "$pid" 2>/dev/null; then
    echo "sterling-launch: could not stop the TUI (pid $pid) in ${from:-a process outside tmux}; the new pane will exit at once" >&2
    return 0
  fi
  echo "sterling-launch: tmux session ${from:-(none, a TUI outside tmux)} lost the TUI (pid $pid); it opens in $1"
  for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
    kill -0 "$pid" 2>/dev/null || return 0
    sleep 0.1
  done
  echo "sterling-launch: the TUI (pid $pid) has not exited after 2s; the new pane may exit at once" >&2
}

# Split the TUI in as a right pane of the session's active window, unless the
# session already shows it. -d: create the pane WITHOUT focusing it, so the
# keyboard stays on the left pane (terminal-kit otherwise grabs all input).
add_tui_pane() {
  if has_tui_pane "$1"; then
    echo "sterling-launch: tmux session $1 already shows the TUI"
    return 0
  fi
  take_tui "$1"
  tmux split-window -h -d -t "=$1:" -c "$WORKDIR" -l "${SPLIT_RATIO}%" \
    "$NODE_BIN" "$TUI_BUNDLE" --store "$STORE"
}

# open_session <session> <command...>: attach when it runs (re-adding a missing
# TUI pane), else create it with the command on the left and the TUI on the right.
open_session() {
  local S="$1"
  shift
  if running "$S"; then
    # Session-scoped (not -g): click-to-focus a pane; Shift+drag still selects
    # plain terminal text. Set again here so an older session picks it up.
    tmux set-option -t "=$S:" mouse on
    add_tui_pane "$S"
    exec tmux attach-session -t "=$S"
  fi
  tmux new-session -d -s "$S" -c "$WORKDIR" "$@"
  tmux set-option -t "=$S:" mouse on
  add_tui_pane "$S"
  tmux select-pane -t "=$S:.0"
  exec tmux attach-session -t "=$S"
}

case "$MODE" in
  claude|up)
    [ -n "$CLAUDE_BIN" ] || { echo "sterling-launch: 'claude' not found on PATH (set CLAUDE_BIN)" >&2; exit 1; }
    # A session from the launcher before the per-checkout names is attached to, never duplicated.
    if ! running "$SESSION-claude" && legacy_running; then
      open_session "$LEGACY_SESSION"
    fi
    open_session "$SESSION-claude" "$CLAUDE_BIN"{{CLAUDE_PLUGIN_FLAG}}
    ;;
  opencode)
    [ -n "$OPENCODE_BIN" ] || { echo "sterling-launch: 'opencode' not found on PATH or in ~/.opencode/bin (set OPENCODE_BIN)" >&2; exit 1; }
    open_session "$SESSION-opencode" "$OPENCODE_BIN"
    ;;
  tui)
    # Inside tmux: the caller's own session. Outside: the Claude Code session,
    # then the OpenCode one, then a session from before the suffix.
    S=""
    if [ -n "${TMUX:-}" ]; then
      S="$(tmux display -p '#S')"
    else
      for candidate in "$SESSION-claude" "$SESSION-opencode"; do
        if running "$candidate"; then S="$candidate"; break; fi
      done
      if [ -z "$S" ] && legacy_running; then S="$LEGACY_SESSION"; fi
    fi
    [ -n "$S" ] || { echo "sterling-launch: no session of this project is running ($SESSION-claude, $SESSION-opencode) - start one with: ./sterling-launch.sh claude" >&2; exit 1; }
    tmux set-option -t "=$S:" mouse on
    add_tui_pane "$S"
    ;;
  *)
    echo "sterling-launch: unknown mode '$MODE' (use claude, opencode or tui)" >&2
    exit 1
    ;;
esac
