@echo off
rem Sterling split launcher (spec §11) — GENERATED by /sterling:init from
rem templates/launcher-win.bat with machine-detected paths. Gitignored
rem (machine-specific); regenerable via /sterling:launcher.
set STERLING_SPLIT=1
{{WT}} -d "%CD%" {{CLAUDE}} ; split-pane -V --size {{SPLIT_RATIO}} -d "%CD%" {{NODE}} "{{TUI_BUNDLE}}" --store "%CD%\.sterling\sterling.db"
