@echo off
rem Sterling NATIVE-Windows launcher - double-click from Explorer: native
rem claude.exe (LEFT) + the Sterling TUI on native Windows node (RIGHT), no WSL.
rem GENERATED by /sterling:init; machine-specific; gitignored; regenerable by
rem re-running /sterling:init. The WSL/tmux variant is sterling.bat.
rem
rem wt.exe is a WindowsApps execution alias - call it by ABSOLUTE path: the
rem WindowsApps dir is NOT reliably on the PATH a double-clicked .bat inherits,
rem so a bare `wt.exe` flashes-and-closes (anti_pattern 6ac730b1). %LOCALAPPDATA%
rem and %USERPROFILE% expand per-user, so the template ships portable; the node
rem path is detected by init via `where.exe node` (needs the node dir on PATH).
rem
rem MCP: native claude can't run the plugin's WSL-node MCP server, so it loads a
rem Windows-node MCP config instead and --strict-mcp-config makes it IGNORE the
rem plugin's (WSL) server. NOTE: --strict means this claude sees ONLY the sterling
rem server (any other global MCP servers are suppressed in this native session).
rem
rem split-pane focuses the new (TUI) pane and wt has no create-unfocused flag, so
rem the trailing `move-focus left` returns the keyboard to the conductor (left)
rem pane - otherwise terminal-kit grabs all input (decisions 6fda899c/5126b77d).
set STERLING_SPLIT=1
"%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe" -d "%CD%" "%USERPROFILE%\.local\bin\claude.exe" --plugin-dir "{{WIN_PLUGIN_DIR}}" --mcp-config "{{WIN_PLUGIN_DIR}}\.claude-plugin\sterling-mcp-win.json" --strict-mcp-config ; split-pane -V --size {{SPLIT_RATIO}} -d "%CD%" "{{WIN_NODE}}" "{{WIN_TUI_BUNDLE}}" --store "%CD%\.sterling\sterling.db" ; move-focus left
