@echo off
rem Sterling split launcher (spec §11) — GENERATED by /sterling:init from
rem templates/launcher-win.bat with machine-detected paths. Gitignored
rem (machine-specific); regenerable via /sterling:launcher.
set STERLING_SPLIT=1
rem split-pane focuses the new (TUI) pane and wt has no create-unfocused flag,
rem so the trailing `move-focus left` returns the keyboard to the conductor
rem (left) pane - otherwise terminal-kit grabs all input (decision 6fda899c).
{{WT}} -d "%CD%" {{CLAUDE}} ; split-pane -V --size {{SPLIT_RATIO}} -d "%CD%" {{NODE}} "{{TUI_BUNDLE}}" --store "%CD%\.sterling\sterling.db" ; move-focus left
