#!/usr/bin/env bash
# Sterling tmux launcher (spec section 11) - the WSL/Linux split session: a left
# pane running claude and a right pane running the TUI. GENERATED by /sterling:init
# from templates/launcher-tmux.sh with machine-detected paths. Machine-specific;
# gitignored; regenerable by re-running /sterling:init. Both .bat entry points
# (sterling.bat / tui.bat) call this script through WSL.
#
# Usage:
#   sterling-launch.sh        full split session (or re-attach if already running)
#   sterling-launch.sh tui    re-add the TUI pane to the running session
set -euo pipefail

MODE="${1:-up}"
SESSION="{{SESSION}}"   # per-project: multiple projects at once, never one twice

# --- generated paths (machine-detected by init) ---
PLUGIN_DIR="{{PLUGIN_DIR}}"
TUI_BUNDLE="{{TUI_BUNDLE}}"
SPLIT_RATIO={{SPLIT_RATIO}}   # right-pane width, percent

# node/claude resolved at runtime (PATH first, then the ~/.local tarball install)
CLAUDE_BIN="${CLAUDE_BIN:-$(command -v claude || true)}"
NODE_BIN="${NODE_BIN:-$(command -v node || true)}"
[ -n "$NODE_BIN" ] || NODE_BIN="$(ls -d "$HOME"/.local/node-v*-linux-x64/bin/node 2>/dev/null | head -1)"

WORKDIR="$PWD"
STORE="$WORKDIR/.sterling/sterling.db"

# --- fail loud on missing inputs (P5) ---
[ -n "$NODE_BIN" ] || { echo "sterling-launch: 'node' not found on PATH (set NODE_BIN)" >&2; exit 1; }
command -v tmux >/dev/null || { echo "sterling-launch: 'tmux' not installed" >&2; exit 1; }
[ -f "$TUI_BUNDLE" ] || { echo "sterling-launch: TUI bundle missing: $TUI_BUNDLE" >&2; exit 1; }
[ -f "$STORE" ]      || { echo "sterling-launch: store missing: $STORE (run from a project root)" >&2; exit 1; }

export STERLING_SPLIT=1

# Re-split the TUI as a right pane in the session's active window.
# -d: create the pane WITHOUT focusing it, so the keyboard stays on the claude
# pane (terminal-kit otherwise grabs all input and you can't type to claude).
add_tui_pane() {
  tmux split-window -h -d -t "$SESSION" -c "$WORKDIR" -l "${SPLIT_RATIO}%" \
    -e STERLING_SPLIT=1 "$NODE_BIN" "$TUI_BUNDLE" --store "$STORE"
}

case "$MODE" in
  tui)
    tmux has-session -t "$SESSION" 2>/dev/null \
      || { echo "sterling-launch: session '$SESSION' not running - start it with: sterling-launch.sh" >&2; exit 1; }
    add_tui_pane
    ;;
  up)
    [ -n "$CLAUDE_BIN" ] || { echo "sterling-launch: 'claude' not found on PATH (set CLAUDE_BIN)" >&2; exit 1; }
    # Idempotent: this project already running -> just attach (never a duplicate).
    if tmux has-session -t "$SESSION" 2>/dev/null; then
      exec tmux attach-session -t "$SESSION"
    fi
    tmux new-session -d -s "$SESSION" -c "$WORKDIR" "$CLAUDE_BIN" --plugin-dir "$PLUGIN_DIR"
    add_tui_pane
    tmux select-pane -t "$SESSION".0
    exec tmux attach-session -t "$SESSION"
    ;;
  *)
    echo "sterling-launch: unknown mode '$MODE' (use no arg, or 'tui')" >&2
    exit 1
    ;;
esac
