@echo off
rem Sterling NATIVE-Windows launcher - double-click from Explorer: native
rem claude.exe (LEFT) + the Sterling TUI on native Windows node (RIGHT).
rem GENERATED by /sterling:init; machine-specific; gitignored; regenerable by
rem re-running /sterling:init. The tmux variant is sterling.bat.
rem
rem Windows Terminal is a WindowsApps execution alias - call it by ABSOLUTE path:
rem the WindowsApps dir is NOT reliably on the PATH a double-clicked .bat inherits,
rem so a bare invocation flashes-and-closes (anti_pattern 6ac730b1). %LOCALAPPDATA%
rem and %USERPROFILE% expand per-user, so the template ships portable; the node
rem path is baked by init from process.execPath on a native-Windows host (decision
rem host-native-init-with-dev-machine-escape-hatch) - no PATH lookup is involved,
rem because that interpreter IS the running process. A PATH probe was measured
rem unreliable on the real native host (research_finding
rem native-windows-platform-measurements-2026-08-27: `where.exe node` finds nothing
rem there even though node runs fine by absolute path).
rem
rem MCP IS MODE-DEPENDENT; init renders the flags into {{MCP_ARGS}}:
rem   host-native  - adds NOTHING. claude loads sterling from --plugin-dir and every
rem                  other MCP server the user has (codex included) still loads.
rem                  This is the default for a Windows-only installation.
rem   dual-context - adds --mcp-config <win json> --strict-mcp-config, because on a
rem                  MIXED host the plugin's own entry names a Linux interpreter that
rem                  Windows cannot execute. The cost is that --strict makes this
rem                  claude see ONLY the sterling server (decision 67350de4 CAVEAT 1)
rem                  - paid only where that premise still holds.
{{MCP_MODE_NOTE}}
rem
rem split-pane focuses the new (TUI) pane and wt has no create-unfocused flag, so
rem the trailing `move-focus left` returns the keyboard to the conductor (left)
rem pane - otherwise terminal-kit grabs all input (decisions 6fda899c/5126b77d).
rem
rem NO DOMAIN-SNAPSHOT BRIDGE, DELIBERATELY (board 3873d33b). This launcher used to
rem run a snapshot step through the WSL side first, because a native process cannot
rem live-read WSL-resident WAL domain stores (research_finding 5c6437d8). That step
rem only ever served a MIXED host: packages/store/src/mounted.ts derives the domains
rem root from homedir(), so a Windows-only user's native server and native TUI
rem already open %USERPROFILE%\.sterling\domains directly, with no boundary to
rem cross. The ruling that a Windows installation invokes no WSL anywhere is
rem unconditional, so the step is gone in BOTH modes.
rem scripts/snapshot-domains-for-windows.mjs stays on disk as a hand-run legacy tool
rem for a mixed host; it is no longer on any launch path.
"%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe" -d "%CD%" "%USERPROFILE%\.local\bin\claude.exe" --plugin-dir "{{WIN_PLUGIN_DIR}}"{{MCP_ARGS}} ; split-pane -V --size {{SPLIT_RATIO}} -d "%CD%" "{{WIN_NODE}}" "{{WIN_TUI_BUNDLE}}" --store "%CD%\.sterling\sterling.db" ; move-focus left
