@echo off
rem Sterling NATIVE-Windows launcher - double-click from Explorer: native
rem claude.exe (LEFT) + the Sterling TUI on native Windows node (RIGHT), no WSL.
rem GENERATED by /sterling:init; machine-specific; gitignored; regenerable by
rem re-running /sterling:init. The WSL/tmux variant is sterling.bat.
rem
rem Windows Terminal is a WindowsApps execution alias - call it by ABSOLUTE path:
rem the WindowsApps dir is NOT reliably on the PATH a double-clicked .bat inherits,
rem so a bare invocation flashes-and-closes (anti_pattern 6ac730b1). %LOCALAPPDATA%
rem and %USERPROFILE% expand per-user, so the template ships portable; the node
rem path is detected by init via `where.exe node` (needs the node dir on PATH).
rem
rem MCP: native claude can't run the plugin's WSL-node MCP server, so it loads a
rem Windows-node MCP config instead and --strict-mcp-config makes it IGNORE the
rem plugin's (WSL) server. NOTE: --strict means this claude sees ONLY the sterling
rem server (any other global MCP servers are suppressed in this native session).
rem
rem split-pane focuses the new (TUI) pane and wt has no create-unfocused flag, so
rem the trailing `move-focus left` returns the keyboard to the conductor (left)
rem pane - otherwise terminal-kit grabs all input (decisions 6fda899c/5126b77d).
rem
rem DOMAIN-KNOWLEDGE SNAPSHOT BRIDGE (P5, AC8): a native-Windows process cannot
rem live-read the WSL-resident WAL domain stores (research_finding 5c6437d8:
rem WAL-over-9p `database is locked`). So first, on the WSL side, VACUUM-INTO a
rem fresh snapshot of each domain store into the Windows-local default path
rem (%USERPROFILE%\.sterling\domains, translated to /mnt/c by wslpath); the native
rem TUI then opens those local-NTFS snapshots (P4 skip-missing tolerates absence).
rem FAIL-SOFT: this is a SEPARATE statement, NOT &&-chained onto the launch - a
rem snapshot failure leaves stale/absent snapshots but never blocks the panes.
rem The WSL launcher is invoked BARE (it lives in System32, reliably on PATH -
rem unlike Windows Terminal it must NOT be given an absolute path, anti_pattern
rem e7a46e35).
wsl.exe -- bash -lic "node '{{SNAPSHOT_SCRIPT}}' --target '{{PROJECT_DIR_POSIX}}' --win-domains-root \"$(wslpath '%USERPROFILE%')/.sterling/domains\""
"%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe" -d "%CD%" "%USERPROFILE%\.local\bin\claude.exe" --plugin-dir "{{WIN_PLUGIN_DIR}}" --mcp-config "{{WIN_PLUGIN_DIR}}\.claude-plugin\sterling-mcp-win.json" --strict-mcp-config ; split-pane -V --size {{SPLIT_RATIO}} -d "%CD%" "{{WIN_NODE}}" "{{WIN_TUI_BUNDLE}}" --store "%CD%\.sterling\sterling.db" ; move-focus left
