#!/usr/bin/env bash
# Sterling {{APP}} opener ({{APP}} + TUI, via sterling-launch.sh). GENERATED by /sterling:init; gitignored.
# Run it from a terminal, or double-click it (Run as a Program) to open a new terminal window.
cd "$(dirname "$0")" || exit 1
[ -t 1 ] && exec bash ./sterling-launch.sh {{MODE}}
run=(bash -c 'bash ./sterling-launch.sh {{MODE}} || read -rp "sterling-launch failed. Press Enter to close. "')
for t in ghostty gnome-terminal kitty konsole x-terminal-emulator; do
  command -v "$t" >/dev/null || continue
  case "$t" in
    ghostty) set -- --working-directory="$PWD" -e ;; gnome-terminal) set -- --working-directory="$PWD" -- ;;
    kitty) set -- --directory "$PWD" ;; konsole) set -- --workdir "$PWD" -e ;; *) set -- -e ;;
  esac
  exec setsid -f "$t" "$@" "${run[@]}" >/dev/null 2>&1 </dev/null
done
msg="Sterling: no terminal found (tried ghostty, gnome-terminal, kitty, konsole, x-terminal-emulator). Run $0 from a terminal."
command -v notify-send >/dev/null && notify-send "Sterling" "$msg"; echo "$msg" >&2; exit 1
