@echo off
rem Sterling TUI re-opener - double-click to re-add the TUI pane to this
rem project's RUNNING tmux session (use after closing the pane with q).
rem GENERATED by /sterling:init; machine-specific; gitignored.
wsl.exe --cd "{{WIN_PROJECT_DIR}}" -- bash -lic "./sterling-launch.sh tui"
