@echo off
rem Sterling TUI pane launcher (spec section 11, the section 13 dashboard
rem command) - GENERATED by /sterling:init from templates/tui-win.bat with
rem machine-detected paths. Gitignored (machine-specific); regenerable by
rem re-running /sterling:init. Opens the TUI as a fresh split in the CURRENT
rem Windows Terminal window - use after closing the pane with q.
rem wt focuses the newly-split pane and has no create-unfocused flag, so the
rem chained `move-focus left` returns the keyboard to the conductor (left)
rem pane - otherwise terminal-kit grabs all input (decision 6fda899c).
{{WT}} -w 0 split-pane -V --size {{SPLIT_RATIO}} -d "%CD%" {{NODE}} "{{TUI_BUNDLE}}" --store "%CD%\.sterling\sterling.db" ; move-focus left
