@echo off
rem Sterling updater, WSL CHAIN - double-click from Explorer to bring this machine's
rem Sterling clone to origin's default branch (fast-forward + rebuild + agent
rem sync), with NO Claude session in the loop. GENERATED by /sterling:init (and
rem ensured by /sterling:update's project fan-out); machine-specific; gitignored;
rem regenerable. The logic lives in the clone (scripts/update.mjs); the console
rem wrapper (scripts/update-console.sh) holds the window open so the outcome -
rem refusal, failure, or the restart instruction - can actually be read.
rem wt.exe by absolute path: the WindowsApps dir is NOT reliably on the PATH a
rem double-clicked .bat inherits, so a bare `wt.exe` flashes-and-closes.
rem `bash scripts/...` (not ./scripts/...) so a clone on ext4 without the exec
rem bit still runs; drvfs clones are executable-by-default either way.
rem THIS TEMPLATE IS ONLY RENDERED BY A WSL/LINUX HOST. A native-Windows host has
rem no WSL to shell into and renders templates/update-win-native.bat instead
rem (same generated filename; see scripts/lib/update-launcher.mjs).
"%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe" wsl.exe --cd "{{WIN_PLUGIN_DIR}}" -- bash -lic "bash scripts/update-console.sh"
