@echo off
rem Sterling updater, NATIVE WINDOWS - double-click from Explorer to bring this
rem machine's Sterling clone to origin's default branch (fast-forward + rebuild +
rem agent sync), with NO Claude session in the loop and NO WSL anywhere in the
rem chain. GENERATED by /sterling:init (and ensured by /sterling:update's project
rem fan-out); machine-specific; gitignored; regenerable.
rem
rem The WSL sibling (templates/update-win.bat) shells to wsl.exe + bash
rem scripts/update-console.sh; a 100%-Windows user has no WSL, and the clone
rem update is the ONLY way a consuming machine receives Sterling changes
rem (decisions e6240afe, ffe7c416, 1fe2a5e3). So this template is chosen instead
rem whenever the RENDERING host is win32. There is no native counterpart of
rem update-console.sh and there must not be: the whole updater already lives in
rem node (scripts/update.mjs), and cmd.exe can hold its own window open - so the
rem console duties (outcome line + pause) are the five lines below, not a port.
rem
rem NODE IS BAKED, NOT LOOKED UP: node is measurably NOT on the PATH a
rem double-clicked .bat inherits on this host class (ffe7c416 defect 1), so the
rem absolute path of the node that RENDERED this file - already proven runnable,
rem needing no PATH membership - is baked in, with a PATH lookup only as the
rem fallback for a moved/upgraded install. No wt.exe: a double-clicked .bat
rem already owns a console window, so nothing needs a terminal host.
setlocal
title Sterling updater
set "STERLING_CLONE={{WIN_PLUGIN_DIR}}"
set "STERLING_NODE={{WIN_NODE_EXE}}"

if not exist "%STERLING_CLONE%\scripts\update.mjs" goto noclone
if exist "%STERLING_NODE%" goto havenode
where node >nul 2>&1
if errorlevel 1 goto nonode
set "STERLING_NODE=node"

:havenode
cd /d "%STERLING_CLONE%"
"%STERLING_NODE%" "scripts\update.mjs" %*
set "STATUS=%ERRORLEVEL%"
echo.
if "%STATUS%"=="0" goto ok
echo -- Update did NOT complete (exit %STATUS%). The message above names the defect and where it gets fixed - nothing was half-applied.
goto done

:ok
echo -- Update finished. If it applied changes, RESTART any open Sterling sessions.
goto done

:noclone
echo sterling-update: the Sterling clone is not at "%STERLING_CLONE%" (no scripts\update.mjs there).
echo Nothing was changed. Re-run /sterling:init in this project to regenerate this launcher, or move the clone back.
set "STATUS=1"
goto done

:nonode
echo sterling-update: node was not found at "%STERLING_NODE%" and is not on the PATH.
echo Nothing was changed. Install Node.js (or re-run /sterling:init from a session whose node still exists) and try again.
set "STATUS=1"

:done
pause
exit /b %STATUS%
