// Bundle the TUI (spec §11): esbuild single file, zero runtime node_modules
// resolution — the standalone launch path has no SessionStart hook to heal
// the environment, so there must be nothing to repair.
// Requires built packages (npm run build).
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

await build({
  entryPoints: [join(root, 'packages', 'tui', 'dist', 'main.js')],
  outfile: join(root, 'packages', 'tui', 'bundle', 'sterling-tui.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  // ink imports react-devtools-core behind a DEV-only guard; shim it empty
  alias: { 'react-devtools-core': join(here, 'lib', 'empty-shim.mjs').replace(/\\/g, '/') },
  // react/ink resolve at build time and are inlined; node: builtins stay external
  banner: {
    js: '// GENERATED by scripts/build-tui.mjs — single-file Sterling TUI; do not edit.\nimport { createRequire } from "node:module"; const require = createRequire(import.meta.url);',
  },
});
console.log('bundled: packages/tui/bundle/sterling-tui.mjs');
