// Bundle hook scripts for shipping (CLAUDE.md invariant 4, spec §2.2):
// scripts/hooks/h*.mjs (which import workspace packages at author time) become
// standalone single-file hooks/<name>.mjs with no workspace imports at runtime.
// Requires built packages (npm run build) — bundles resolve package dist files.
import { build } from 'esbuild';
import { readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { inFlightAdvisory } from './lib/dispatch-register.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const srcDir = join(here, 'hooks');

// Wave-settle disclosure (board 54c451b4): a mid-wave bundle rebuild can race a
// coder's in-flight source edit (the 6ef262fc shape). Advisory only — never a gate.
const advisory = inFlightAdvisory(root, 'a bundle rebuilt now may race an in-flight edit of scripts/hooks sources.');
if (advisory) console.log(`build-hooks: ${advisory}`);

const entries = readdirSync(srcDir).filter((f) => f.startsWith('h') && f.endsWith('.mjs'));
for (const entry of entries) {
  await build({
    entryPoints: [join(srcDir, entry)],
    outfile: join(root, 'hooks', entry),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node24',
    banner: { js: '// GENERATED by scripts/build-hooks.mjs — do not edit; edit scripts/hooks/ and rebuild.' },
  });
  console.log(`bundled: hooks/${entry}`);
}
