// Bundle hook scripts for shipping (CLAUDE.md invariant 4, spec §2.2):
// scripts/hooks/h*.mjs (which import workspace packages at author time) become
// standalone single-file hooks/<name>.mjs with no workspace imports at runtime.
// Requires built packages (npm run build) — bundles resolve package dist files.
//   node scripts/build-hooks.mjs [--src-dir <dir>] [--out-dir <dir>]
// --out-dir builds somewhere OTHER than the live hooks/ surface. A test that
// needs a built bundle must use it: building in place puts whatever is in
// scripts/hooks/ live on disk for every subsequent hook call of the running
// session, which turns a mutation battery into a shipped sabotage (board
// 3e569411).
// --src-dir READS from somewhere other than the live scripts/hooks/ sources —
// the containment prerequisite of the hollow-test mutation arm (decision
// 1dab2a9f, anti_pattern 37b3cb0a severity BLOCK). Without it a build always
// compiles the LIVE sources, so mutating a clean-room copy changes nothing and
// every mutant reports SURVIVED against unmutated source. The clean room lives
// in the OS tmpdir (mkdtemp; the git-worktree alternative is REJECTED by
// anti_pattern e2a1fee8), which is outside ordinary node resolution — see
// nodePaths below.
import { build } from 'esbuild';
import { readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve, relative } from 'node:path';
import { inFlightAdvisory } from './lib/dispatch-register.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

// Parsed STRICTLY: an unrecognized or malformed argument must refuse, never
// fall through to the default — the default writes the LIVE enforcement
// surface, so `--outdir` for `--out-dir` would silently do the one thing the
// flag exists to prevent (P5, fail loud). The same holds for `--src-dir`: a
// missing, nonexistent or not-a-directory value falling back to
// scripts/hooks/ is exactly the in-place READ the flag exists to prevent, so
// each refuses before anything is emitted.
const args = process.argv.slice(2);
let outDir = join(root, 'hooks');
let srcDir = join(here, 'hooks');
for (let i = 0; i < args.length; i++) {
  const flag = args[i];
  if (flag !== '--out-dir' && flag !== '--src-dir') {
    console.error(`build-hooks: unrecognized argument '${flag}' — usage: build-hooks.mjs [--src-dir <dir>] [--out-dir <dir>]`);
    process.exit(1);
  }
  const value = args[++i];
  if (!value || value.startsWith('--')) {
    console.error(`build-hooks: ${flag} requires a directory argument`);
    process.exit(1);
  }
  if (flag === '--out-dir') {
    outDir = resolve(value);
    continue;
  }
  const candidate = resolve(value);
  let stat;
  try {
    stat = statSync(candidate);
  } catch {
    console.error(`build-hooks: --src-dir '${candidate}' does not exist — refusing rather than falling back to the live sources`);
    process.exit(1);
  }
  if (!stat.isDirectory()) {
    console.error(`build-hooks: --src-dir '${candidate}' is not a directory — refusing rather than falling back to the live sources`);
    process.exit(1);
  }
  srcDir = candidate;
}

// Wave-settle disclosure (board 54c451b4): a mid-wave bundle rebuild can race a
// coder's in-flight source edit (the 6ef262fc shape). Advisory only — never a gate.
const advisory = inFlightAdvisory(root, 'a bundle rebuilt now may race an in-flight edit of scripts/hooks sources.');
if (advisory) console.log(`build-hooks: ${advisory}`);

const entries = readdirSync(srcDir).filter((f) => f.startsWith('h') && f.endsWith('.mjs'));
for (const entry of entries) {
  await build({
    entryPoints: [join(srcDir, entry)],
    outfile: join(outDir, entry),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node24',
    // The workspace packages (@sterling/schemas, @sterling/store) always resolve
    // from THIS repo's node_modules, whatever --src-dir points at. A relocated
    // source tree in the OS tmpdir has no node_modules above it, so ordinary
    // resolution would fail; nodePaths is the NODE_PATH-equivalent fallback and
    // is consulted only after normal resolution, so the default build is
    // unchanged. Deliberate: the clean room mutates HOOK SOURCES, never the
    // workspace packages, so the packages must come from the real tree —
    // unlike the worktree shape anti_pattern e2a1fee8 rejects, where a
    // symlinked node_modules silently swapped the SOURCE tree under the build.
    nodePaths: [join(root, 'node_modules')],
    banner: { js: '// GENERATED by scripts/build-hooks.mjs — do not edit; edit scripts/hooks/ and rebuild.' },
  });
  console.log(`bundled: ${relative(root, join(outDir, entry)).split('\\').join('/')}`);
}
