// Bundle the TUI (spec §11): esbuild single file, zero runtime node_modules
// resolution — the standalone launch path has no SessionStart hook to heal
// the environment, so there must be nothing to repair.
// Requires built packages (npm run build).
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

await build({
  entryPoints: [join(root, 'packages', 'tui', 'dist', 'main.js')],
  outfile: join(root, 'packages', 'tui', 'bundle', 'sterling-tui.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  // terminal-kit's lazy requires are bundler-hostile; it ships a static entry
  // (termkit-no-lazy-require.js) for exactly this case. The alias covers the
  // package import; the onLoad rewrite makes INTERNAL require('./termkit.js')
  // calls delegate to the same static entry (its own runtime check cannot work
  // inside a bundle). The README stub keeps the termconfig glob bundleable.
  alias: { 'terminal-kit': 'terminal-kit/lib/termkit-no-lazy-require.js' },
  plugins: [
    {
      name: 'terminal-kit-static',
      setup(b) {
        b.onLoad({ filter: /terminal-kit[\\/]lib[\\/]termkit\.js$/ }, () => ({
          contents: "module.exports = require('./termkit-no-lazy-require.js');",
          loader: 'js',
          resolveDir: join(root, 'node_modules', 'terminal-kit', 'lib'),
        }));
        b.onLoad({ filter: /termconfig[\\/]README$/ }, () => ({ contents: 'module.exports = {};', loader: 'js' }));
      },
    },
  ],
  // react/ink resolve at build time and are inlined; node: builtins stay external
  banner: {
    js: [
      '// GENERATED by scripts/build-tui.mjs — single-file Sterling TUI; do not edit.',
      'import { createRequire as __cr } from "node:module"; const require = __cr(import.meta.url);',
      'import { fileURLToPath as __f2p } from "node:url"; import { dirname as __dn } from "node:path";',
      'const __filename = __f2p(import.meta.url); const __dirname = __dn(__filename);',
    ].join('\n'),
  },
});
console.log('bundled: packages/tui/bundle/sterling-tui.mjs');
